### ISSUE TITLE
Touchpad horizontal scroll translates to back/forward

### ISSUE THREAD

**Issue by grawity** [FreeRDP/FreeRDP#2302]
On a laptop, the touchpad supports both vertical and horizontal scrolling using a two-finger gesture. That is, even when I'm scrolling vertically, it is very easy to accidentally activate horizontal scroll.

Unfortunately, with FreeRDP on Linux/X11, the "horizontal scroll" events somehow get interpreted as additional mouse buttons and result in "back"/"forward" navigation. So whenever I'm trying to scroll a list or a page, I keep accidentally navigating backwards or forwards in history.

I don't know if this is a RDP thing or a FreeRDP thing or even an X11 thing (the servers are Windows 2011 SBS and 2012 R2), but if it is somehow possible to disable this behavior, that'd be at the top of my wishlist.

(Currently I just disable horiz scroll system-wide on the client OS, but that's far from ideal...)

**Comment by colemickens** [comment]
This is very, very, very frustrating. How can we disable horizontal scroll events from being transmitted?

**Comment by colemickens** [comment]
Can someone (@hardening, @awakecoding, @akallabeth) point me in the right direction for how I might about ignoring horizontal scroll events?

This issue is a big problem on any laptop. I'd like to see it fixed and help out if I can.

**Comment by colemickens** [comment]
Ping again. This is unusable with libinput becoming the standard. There's no way to disable horizontal scroll events with this new input driver.

**Comment by bsagal** [comment]
The horizontal scroll register with X as buttons 6 and 7

**Comment by bmiklautz** [comment]
@colemickens what version of FreeRDP are you using?

**Comment by bsagal** [comment]
the following patch removes the problem (it affects master, not sending a pull request as the patch is only a workaround and not a real solution)
```diff
--- a/client/X11/xf_event.c
+++ b/client/X11/xf_event.c
@@ -334,14 +334,14 @@ BOOL xf_generic_ButtonPress(xfContext* xfc, int x, int y, int button, Window win
                        flags = PTR_FLAGS_WHEEL | PTR_FLAGS_WHEEL_NEGATIVE | 0x0088;
                        break;
 
-               case 6:         /* wheel left or back */
+//             case 6:         /* wheel left or back */
                case 8:         /* back */
                case 97:        /* Xming */
                        extended = TRUE;
                        flags = PTR_XFLAGS_DOWN | PTR_XFLAGS_BUTTON1;
                        break;
 
-               case 7:         /* wheel right or forward */
+//             case 7:         /* wheel right or forward */
                case 9:         /* forward */
                case 112:       /* Xming */
                        extended = TRUE;
```

**Comment by bsagal** [comment]
fixed in commit 23fea16

**Comment by ardichoke** [comment]
This is still listed as open and I'm still having the exact problem listed under Fedora 24 running freerdp v 2.0.0-dev. Has anyone confirmed that the above commit actually fixes the issue?

**Comment by bsagal** [comment]
from what i can tell (I do not know much about fedora packaging) Fedora 24 uses the tree at commit b02943a, which is before commit 23fea16.

Please try building from source to see if the problem is fixed

**Comment by cfstras** [comment]
For everybody just trying to find a workaround to disable back/forward emulation (on any mouse/touchpad), just go:

    xinput list   # find your touchpads ID
    xinput get-button-map <id>  # to check what it was before
    xinput set-button-map <id> 1 2 3 4 5 0 0 9 10 11 12 13 14 15 16 17 18 19 20
    # note that 6 and 7 are mapped to 0, which disables them.
see also: https://wiki.archlinux.org/index.php/Libinput

**Comment by akallabeth** [comment]
Closing as confirmed fixed by @bsagal
