### ISSUE TITLE
multimon smart-sizing correct, but in fullscreen shows display on primary monitor only

### ISSUE THREAD

**Issue by user1007017** [FreeRDP/FreeRDP#2707]
Hi 
I'm experiencing the following issue: Multimon smart-sizing is correct but in fullscreen displays whole screen only on primary monitor 
The whole screen 1920x1200+2560x1440 is in fullscreen forced to 1920x1200 (shrinks)

I have to mention that it did work earlier.
What can cause this issue?

BTW Client is Windows 8.1

```
[12:55:56:730] [19161:19162] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
 [12:55:56:751] [19161:19162] [ERROR][com.freerdp.core.gcc] - WARNING: true multi monitor support was not advertised by server!
 [12:55:56:751] [19161:19162] [ERROR][com.freerdp.core.gcc] - Sending multi monitor information anyway (may break connectivity!)


My config:
 xfreerdp --version
This is FreeRDP version 1.2.4-dev (git c8731ea)

 xfreerdp --monitor-list
      * [0] 1920x1200   +0+0
        [1] 2560x1440   +1920+0

/usr/local/bin/xfreerdp /f /rfx /cert-ignore /v:192.168.1.xxx /u:xxxxx /p:xxxxx /sec:rdp  +smart-sizing /multimon:force -sec-nla +clipboard +fonts

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:    14.04
Codename:   trusty
```

**Comment by bmiklautz** [comment]
@b987123 you mean the server is windows 8.1?

**Comment by b987123** [comment]
@bmiklautz 
Thanks, yes, the "server"  (client) with the rdp-server
I have now compiled FreeRDP version 1.1.0-beta1 (git 1.1.0-beta+2013071101-162-g770c67)
and there fullscreen span worked flawless. 

I've tried FreeRDP version 1.2.3-dev and 1.2.4-dev (git c8731ea) but there is the problem as mentioned.

**Comment by giovannitarter** [comment]
Hi. 
I'm experiencing a similar issue on the Linux Client. 
The /multimon parameter makes xfreerdp spawn a fullscreen window only on the primary monitor when using WM openbox 3.5 and 3.6. 
Using metacity as WM, the fullscreen window is displayed on both monitors. 

The regression was introduced on commit bad2f138c183b84c996ec16b4f2e0aaf77b54d7c, the issue is not present on the commits before.

Config:
$tmp/freerdp/bin/xfreerdp --version
This is FreeRDP version 1.2.4-dev (git d65cc5d)

$/tmp/freerdp/bin/xfreerdp /v:******* /u:******* /multimon

$/tmp/freerdp/bin/xfreerdp --monitor-list 
* [0] 1920x1080   +1920+0
  [1] 1920x1080   +0+0

**Comment by nicon8** [comment]
Any news to support Openbox in the future development? I experienced the same issues with the multimon setup

**Comment by CaseyRedisAtWork** [comment]
I have the same issue running from the latest source and have for several months I believe.
>This is FreeRDP version 1.2.4-dev (git c12bc0e)

The same command line against the package for my system, version below, works without issue.  I too am running openbox as the WM (lxde desktop)

>This is FreeRDP version 1.2.0-beta1 (git n/a)

**Comment by avollmerhaus** [comment]
I am experiencing this, too.
This is FreeRDP version 1.2.1-dev (git n/a) and Fluxbox 1.3.7

**Comment by cmsmith1977** [comment]
I'm having this same problem - only get video on the primary display.  If I compile eb14ab15f5bca5751d8a71965f31509d4c3b176b from April 14 fullscreen on dual monitors works, but when I add in bad2f138c183b84c996ec16b4f2e0aaf77b54d7c, it breaks.

**Comment by cmsmith1977** [comment]
I was able to rollback client/X11/xf_window.c to eb14ab15f5bca5751d8a71965f31509d4c3b176b and recompile to make FreeRDP start in fullscreen mode across all monitors again.  Not sure what all ramifications that might have - perhaps @nfedera could weigh in on this?

**Comment by nfedera** [comment]
@cmsmith1977 please ...
- output of xfreerdp --monitor-list
- what window manager ?
- full xfreerdp command line used

**Comment by nfedera** [comment]
@giovannitarter and @cmsmith1977 - Here is what happened:
@bjcollins created the nice pull request #2426 (commit d4a9a2d) which provided many fullscreen and multimon enhancements. This commit removed the override_redirect approach (which worked with basically all window managers) and used the modern way using NET_WM_STATE_FULLSCREEN  and NET_WM_FULLSCREEN_MONITORS for multimon support.
This means that for fullscreen involving multiple monitors the window manager *must* support the NET_WM_FULLSCREEN_MONITORS property - which is not the case for many older wm like openbox, icewm, etc. @awakecoding obviously accepted to drop legacy wm support for /multimon  and merged this PR.
My commits bad2f13 and eb14ab1 were done many weeks later and brought some smart-sizing fixes. IMO it is impossible that /multimon worked with openbox on commit eb14ab1 because the override_redirect support was already removed at this time.

So if my point of view is correct I suggest to close this issue and to open a new feature-request issue for adding /multimon support for window managers that do not support  NET_WM_FULLSCREEN_MONITORS based on the old override_redirect approach.

**Comment by bjcollins** [comment]
@nfedera Your synopsis makes sense to me. Although my PR made improvements for WMs which support NET_WM_FULLSCREEN_MONITORS, it broke support on the WMs which do not support it. I did not take this into account and I do not know if @awakecoding was aware of the "regression" from the PR. I think handling this case should be relatively simple as I believe you can query whether NET_WM_FULLSCREEN_MONITORS is available and act accordingly. I will plan to look at this when I can carve out some time.

**Comment by nfedera** [comment]
@bjcollins you are absolutely right. NET_WM_FULLSCREEN_MONITORS can be queried which means that we could autodetect the requirement for the override_redirect fallback.

**Comment by hardening** [comment]
\<stupid comment\>
@cmsmith1977 @nfedera sounds obvious that commit https://github.com/FreeRDP/FreeRDP/commit/bad2f138c183b84c996ec16b4f2e0aaf77b54d7c is bad :)
Ok I'm ===> [ ]
\</stupid comment\>

**Comment by cmsmith1977** [comment]
@nfedera - a little late on the response, sorry.

* output of xfreerdp --monitor-list

```
user@host:~$ xfreerdp --monitor-list
      * [0] 1920x1080   +0+0
        [1] 1920x1080   +1920+0
```

* what window manager ?
** LXDE 0.7.2 in lubuntu 15.04

* full xfreerdp command line used

```
   xfreerdp /v:192.168.1.1 /sec:tls /u:"" /p:"" /network:lan /sound:sys:alsa /cert-ignore +fonts +decorations +aero +menu-anims /f /multimon
```
* exact remote server os
** Windows 2012 R2 Standard with ThinStuff XP/VS

**Comment by cmsmith1977** [comment]
and I want to re-iterate, that if I do the following, I am able to run in fullscreen across 2 monitors in LXDE.

```
git checkout eb14ab15f5bca5751d8a71965f31509d4c3b176b client/X11/xf_window.c
```
Update line 901 to this:
```
// void xf_SetWindowVisibilityRects(xfContext* xfc, xfAppWindow* appWindow, RECTANGLE_16* rects, int nrects)
void xf_SetWindowVisibilityRects(xfContext* xfc, xfAppWindow* appWindow, UINT32 rectsOffsetX, UINT32 rectsOffsetY, RECTANGLE_16* rects, int nrects)
```

**Comment by nfedera** [comment]
@cmsmith1977 this seems to be caused by openbox's special way of handling the size hints in combination with _NET_WM_STATE_FULLSCREEN.
If you comment line 492 and 495 in current master like this ...
```diff
--- a/client/X11/xf_window.c
+++ b/client/X11/xf_window.c
@@ -489,10 +489,10 @@ void xf_ResizeDesktopWindow(xfContext* xfc, xfWindow* window, int width, int hei
        XResizeWindow(xfc->display, window->handle, width, height);

 #ifdef WITH_XRENDER
-       if (!xfc->settings->SmartSizing)
+       //if (!xfc->settings->SmartSizing)
 #endif
        {
-               if (!xfc->fullscreen)
+       //      if (!xfc->fullscreen)
                {
                        size_hints->min_width = size_hints->max_width = width;
                        size_hints->min_height = size_hints->max_height = height;
```
... openbox will also work, but other legacy window managers still won't work.
So the correct way is still implementing @bjcollins' proposal for autodecting _NET_WM_FULLSCREEN_MONITORS support and using the override_redirect flag it it is not supported.

**Comment by ThorbenJ** [comment]
I am running Debian Stable (Jessie) which has KDE 4.14 and had the same problem.

I copied the steps from: cmsmith1977 comment on 21 Nov 2015 https://github.com/FreeRDP/FreeRDP/issues/2707#issuecomment-158584322 and multimon fullscreen now works again.

In addition: the reason I was running a newer version than the freerdp 1.1 in Debian stable, is because that version is even more broken under KDE 4.

Anyway back to freerdp 2.0.0 (git): I just thought it would be useful to know that this bug also affects KDE 4 (and Debian stable)

**Comment by Enverex** [comment]
Just adding a note as this is still an issue as of current GIT and renders multi-monitor unusable in OpenBox (for anyone else that doesn't find this bug before spending hours trying to find out why it doesn't work).

**Comment by Enverex** [comment]
Same issue in Fluxbox.

**Comment by sotho** [comment]
I think I have the same issue: the first screen is shown, but the second one isn't.
My command line:
 xfreerdp /v:... /d:... /u:... /p:...  /multimon
I bisected it to commit 48be081. So for me current master (a0520f8) and reverting that commit fixes the issue. Both screens are used now.
I am using KDE and kwin 5.6.4 from Debian/unstable.

**Comment by RubenKelevra** [comment]
So when does this issue get fixed?

**Comment by RubenKelevra** [comment]
@akallabeth thanks for your answer. Since this bug is in there for a year the question is, when are we able to use multi-monitor-support again?

**Comment by akallabeth** [comment]
@RubenKelevra Well, simple (and probably unsatisfactory answer) as soon as someone finds time to address the issue. What I've seen it is a simple check missing to revert to old behavior, but I'm busy with other stuff :/

**Comment by RubenKelevra** [comment]
Sad. I found a workaround: turn the decorations off, set the resolution manually and the window will pop over everything (like fullscreen) but the window is presented to the rdp-server as one monitor, if the user expands one window this window is stretched over all monitors, which is not the expected behavior for the users.

**Comment by hardening** [comment]
@RubenKelevra from what I understand the other solution is to use a WM that correctly handles the fullscreen window case...

**Comment by Enverex** [comment]
Well you can't use Openbox and you can't use Marco (see https://github.com/FreeRDP/FreeRDP/issues/3395) so which minimalist window manager can be used?

**Comment by Infinality** [comment]
Here is a really messy workaround that seems to work for me in KDE Plasma.

- Launch some lightweight X program of something you'll never use, like xclock:  xclock&
- Go to the System Settings / Window Rules and create a new rule for xclock.  Set it under "Size & Position" to "Force" to your multiple monitor setup's full width and height, "w,h".  Under "Appearance & Fixes" set "No titlebar and frame" to "Force" "Yes".  Save and apply.
- Get the parent ID of the xclock window on a terminal:  PARENTID=`wmctrl -l -x | egrep 'xclock' | awk '{print $1}' | tail -1`
- Launch your normal xfreerdp command, but add this:  /parent-window:$PARENTID     Make sure that you are also using /multimon option.

Not the most elegant solution, but it will work for me until freerdp works again like it used to.

**Comment by jat255** [comment]
I also have this issue using the latest KWin/plasma setup on Arch Linux. I think "it's the WM's fault" is a pretty unsatisfactory answer. It seems like it shouldn't be too hard to just check the current WM against a blacklist and revert to the old behavior. Unfortunately I do not know enough about the codebase (or C) to do this intelligently...

**Comment by Infinality** [comment]
Agreed.  The fact of the matter is that people use KDE plasma, and KDE plasma is doing things a certain way, rightly or wrongly.  I get that it makes for dirtier code, having to support multiple methods, but the code was already written.

**Comment by T3N4K4** [comment]
If anyone is interested I tried to introduce (since we had a similar problem) a new command line parameter (currently named) +openbox to enable support for alternate window managers.

It just disables the function to set the fullscreen state if the parameter is set.
As a matter of fact it does work with openbox AND xfwm4. Without the parameter it still works with xfwm4.

https://github.com/RangeeGmbH/FreeRDP/commit/e8523d10dac86c468ce1e233934db923b6770203

Should not break the code since it is disabled by default and has to be explicitly set.

**Comment by akallabeth** [comment]
Is this still an issue?

**Comment by Infinality** [comment]
On KDE Plasma, I still only get a single monitor.  This is the command I'm using:

/usr/bin/xfreerdp /u:username /p:************** /d:domain +fonts +window-drag /v:host.domain.com:3389 /bpp:32 /rfx +clipboard /multimon /cert-ignore

**Comment by akallabeth** [comment]
@Infinality which version did you test with? Fixes for fullscreen issues have only been merged to master which may not have landed in your distro packages yet.

**Comment by Infinality** [comment]
@akallabeth I'm using the latest git.  I built it again on another system just to make sure and it still has the problem.

**Comment by T3N4K4** [comment]
@Infinality just for confirmation, can you try to set /multimon:force ?

**Comment by akallabeth** [comment]
Just tried it with openbox, the issue seems to be that the XFreeRDP window for the second monitor is placed anywhere just not on the second monitor (The remote machine is correctly working in multimonitor mode)

**Comment by Infinality** [comment]
@T3N4K4 When I use /multimon:force I get a black window on a single monitor (which never shows the login).

**Comment by T3N4K4** [comment]
@akallabeth @Infinality The problem is still with "_NET_WM_STATE_FULLSCREEN" .. you cannot detect it automatically (at least I do not know a way) and some window manager seem not to be on good term with it (do not support it). Therefore I used the "+openbox" command-line in the rangeegmbh branch.

```
/* Set the fullscreen state */
		xf_SendClientEvent(xfc, window->handle, xfc->_NET_WM_STATE, 4,
		                   fullscreen ? _NET_WM_STATE_ADD : _NET_WM_STATE_REMOVE,
		                   xfc->_NET_WM_STATE_FULLSCREEN, 0, 0);
```

If I set +openbox this code above gets disabled ... and for me that worked in openbox..

**Comment by akallabeth** [comment]
Closing as marked as fixed in #4319

**Comment by jat255** [comment]
@akallabeth, even with a fully up-to-date FreeRDP compiled from git, multi-monitor is still not working correctly for me on KDE plasma (like @Infinality) on Arch Linux. If I try with `/multimon` or `/multimon:force`, I get only a black screen on one monitor, and no login prompt. Everything works fine (albeit on one monitor) if I don't use any `/multimon` option.

```
$ xfreerdp --monitor-list
      * [0] 1920x1080   +1920+0
        [1] 1920x1080   +0+0

$ xfreerdp --version
This is FreeRDP version 2.0.0-dev2 (4889652c1)
```

**Comment by jat255** [comment]
Also, apparently the fix in the RangeeGmbh `freerdp_openbox` branch does not fix it for me, either (although apparently it worked for @T3N4K4)

**Comment by T3N4K4** [comment]
@jat255 just for confirmation, did you use the freerdp_openbox branch with /openbox in the commandline?

**Comment by jat255** [comment]
@T3N4K4 I tried, but it was not accepted as an argument. It looks like the branch was changed (although I can't find how it looked previously) to auto-detect the presence of openbox. Either way, it didn't work on my system.

I also tried to brute-force apply the patch by hardcoding the flag that activates that code to `true`, but that did not work either: https://github.com/jat255/FreeRDP/commit/9c3586bdead8f0539ba5f296c1722f2af96af151

**Comment by T3N4K4** [comment]
@jat255 the important part of the openbox fix was that freerdp does not set fullscreen.

https://github.com/RangeeGmbH/FreeRDP/commit/580fff3796d4c744334d0e3fed8f8bdf362f581e this commit still should contain all needed. The branch may be broken since I had to clean up a lot of things and redo our freerdp fork. Sorry for that.

**Comment by jat255** [comment]
@T3N4K4, hmm, interesting. I tried it that way because when I first used it, the `status` parameter was false, so all the code in that `if` block was not run. Both ways did not fix the issue on my system.

I'll try that commit and see if it makes any difference.

**Comment by jat255** [comment]
@T3N4K4 I got that commit compiled, and as I thought, when trying `/multimon` when using the `+openbox` command, FreeRDP connects, but still only shows one window, not multiple monitors like I'd expect.

**Comment by T3N4K4** [comment]
@jat255 I am currently not near any testing environment, can you try to Set /monitors:0,1 in addition to /multimon or /multimon:force?

**Comment by jat255** [comment]
@T3N4K4 just gave it a shot, and that causes the same output on only one monitor (with and without the `force` option)

**Comment by gergamel** [comment]
I just hit this issue after upgrading to Fedora 27 LXDE from a really old Ubuntu (maybe 12?).

Unfortunately, I blew away the old root, so I'm not sure what xfreerdp I had, but /multimon WAS working great (even with different size monitors).

I've cloned the master (db5628f6f) and built it, so I have:
$ git rev-parse HEAD
db5628f6ffe9e9c9d9c5254b0956ddabab4982c1
$ xfreerdp --version
This is FreeRDP version 2.0.0-dev (git n/a)
$ xfreerdp --monitor-list
      * [0] 1920x1080	+1680+0
        [1] 1680x1050	+0+0

The working command I used to run (to connect to a Win7 PC) is:
xfreerdp /u:**** /p:**** /d:**** /v:**** /f /rfx /multimon

It now only ever fills monitor [0] (note in the attached screenshot the windows taskbar is placed weirdly with a black bar beneath it). If I ctrl+alt+enter to leave fullscreen mode, it looks like the smart-sizing is exactly correct (taskbar is still a bit messed up).

It seems like this issue and #4319 are maybe not completely fixed? Or I'm seeing a different flavour of the issue? Happy to pull patches and try them out on this machine any time.

![xfreerdp-multimon-bug](https://user-images.githubusercontent.com/19425058/34614197-9ab05d88-f26b-11e7-839e-c5e7a3f56ad3.jpg)

**Comment by T3N4K4** [comment]
@gergamel did you have /rfx when /multimon Was working? I remember a test of mine when /rfx with different Monitor sizes was not working. But it was sometimes ago (2016).

The Black Bar beneath seem to be the 30px of the Resolution difference.

**Comment by gergamel** [comment]
Okay. For some reason a restart fixed this, I had been doing dnf updates and a kernel update was pending, so I think this might have been a contributing factor.

For information, xfreerdp always seems to direct the Windows session to put the taskbar on monitor [0], even though it seems able to tell that monitor [1] is on the left (the mouse transitions between the monitors as expected). If I add /monitors:1,0 then the windows session puts the taskbar on the second monitor (the one on the left, in my case).

You can note this issue is tested good with a local build of FreeRDP version 2.0.0-dev2 (db5628f6f) on Fedora 27 (4.14.11-300.fc27.x86_64) LXDE.

Great work guys.

**Comment by jat255** [comment]
Even after a reboot, still no luck for me on KDE Plasma with all packages up-to-date.

**Comment by erichoog** [comment]
@jat255 I have a similar setup to you Arch Linux with KDE Plasma and am experiencing the same issue as well.

The remote machine will show it has two monitors in the session but it will only fullscreen to the primary monitor.  If I hit Ctrl+Alt+Enter then it will exit fullscreen and then span across the two monitors.

**Comment by matthewpapa07** [comment]
FreeRDP multiple monitors is broken for me on the latest master. Using arch linux and KDE Plasma. I have tried running plasma with xorg and wayland and get the same result. The issue must be with kwin. 
FreeRDP works fine on the same system with Gnome using wayland as well as xfce using xorg.

One monitor sort of works. Even then the resolution is incorrect in full screen mode unless i specify resolution. Will take a look at the code to see if it is obvious. This is a completely new codebase though so may be like finding a needle in a haystack.

**Comment by T3N4K4** [comment]
@matthewpapa07 did you compile with either xrandr or xinerama or is the xfreerdp /buildconfig using either of them ?
I think there were some changes in a xrandr / xinerama rework in client/X11/xf_monitor.c if I remember it correctly.

I noticed that if you have your monitors aligned wrong like you have to go left on your left monitor to get into the right one, xfreerdp opens on the left but still tries to go right (where nothing is).

**Comment by tibob** [comment]
Same issue here:
when I try to run xrdp with multiple monitor, the first monitor gets a RDP-full screen display, and the second monitor does not display the RDP-Screen. When you press ctrl-alt-enter (exiting Full-Screen), you get both monitors in one big window above both screens.

Environment:
- Virtual Box with two monitors
- Debian Testing (up to date)
- KDE

I've just build freerdp from master (cmake -DCMAKE_INSTALL_PREFIX=/home/tibob/freerdp -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON .; make; make install, as I just wanted to run in in my user folder).

> tibob@paris:~/freerdp/bin$ ./xfreerdp /buildconfig
> This is FreeRDP version 2.0.0-dev2 (14997f96e)
> Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
> Build type:          Debug
> CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g
> Compiler:            GNU, 7.3.0
> Target architecture: x64

Just tell me if you need me to test something for you.

**Comment by akallabeth** [comment]
@tibob Seems to be an issue with KDE only, tried it with fvwm, openbox, gnome, cinnamon and they work.
Only with KDE the fullscreen switching results in this strange behavior.

**Comment by tibob** [comment]
Filled a bug against KWIN: https://bugs.kde.org/show_bug.cgi?id=391778

**Comment by tibob** [comment]
KWIN sees the Bug in FreeRDP code, not in KWIN. I would have loved to help but I am not skilled enough for X11-Coding :-(

**Comment by akallabeth** [comment]
@tibob Thank you for the effort, added a comment to the issue there.

**Comment by jat255** [comment]
@akallabeth I just tried out your fix on the latest FreeRDP git master, and it solved the problem! Looking forward to this being merged in.

**Comment by tibob** [comment]
Thank you very much @akallabeth for fixing this! Works with the merged pull request.

**Comment by matthewpapa07** [comment]
THANK YOU so much @akallabeth
This works flawlessly now with master!!!!!!! Much appreciated.

**Comment by TurboGraphxBeige** [comment]
It may help some people if I post this. 

Using KDE, I had this behavior where the /multimon option spanned the session in all monitors as if it was one big screen. 

xfreerdp /monitor-list
      * [0] 1920x1080   +0+0
        [1] 1920x1080   +1919+0

I noticed the coordinate of monitor [1]. Turns out there was a 1 pixel overlap with the monitors. I just fixed that in Display settings so monitor [1] is positionned at +1920.

Problem solved.

**Comment by AndrewDRX** [comment]
> It may help some people if I post this.
> 
> Using KDE, I had this behavior where the /multimon option spanned the session in all monitors as if it was one big screen.
> 
> xfreerdp /monitor-list
> * [0] 1920x1080 +0+0
> [1] 1920x1080 +1919+0
> 
> I noticed the coordinates of monitor [1] starting at +1919. Turns out there was a 1 pixel overlap with the monitors. I just moved the screen in Display settings so monitor [1] is positionned at +1920.
> 
> Problem solved.

I had a similar issue due to moving the application launcher panel to the top of the KDE Desktop (Kubuntu 20.04). This post tipped me off that it could be an issue in calculating/offsetting the usable size of the monitor.

As a workaround, I changed the application launcher panel to auto-hide, and then the /multimon flag worked fine.

I'll note that it seems like the /multimon flag (and the /span flag) were correctly using the second monitor, but the KDE Desktop on the second monitor appeared to flash and then cover the display of freerdp application on that monitor. So I am not certain if this issue is on the FreeRDP side or the KDE side.

Just posting this as an FYI of a workaround that did the trick for me. Not going to open a ticket.

**Comment by skjerns** [comment]
I have an offset in both of my monitors. It seems like this causes the same issue as well.

```
~ $ xfreerdp /monitor-list                                                                       (base) [0] 13:42:02
      * [0] 1920x1200   +0+241
        [1] 1080x1920   +1920+0

```
