### ISSUE TITLE
wFreeRDP multiple issues

### ISSUE THREAD

**Issue by haklin0816** [FreeRDP/FreeRDP#4537]
Hi,
I have a few issues with wFreeRDP and I have tried with multiple versions found here:
https://ci.freerdp.com/job/freerdp-nightly-windows/arch=win64,label=vs2013/
And from here:
https://cloudbase.it/freerdp-for-windows-nightly-builds/

*First of all i'm not getting any console output from wfreerdp not even wfreerdp /help or /version.

* I cannot connect any rdp sessions from Windows server 2012 or 2016.
wfreerdp /v:Myip  - asks for user and password and then dies.
wfreerdp /v:Myip /u:Myuser /:uMypassword - dies right away

*Connection from a Windows 7/10 machine works better but only when using IP, Computer name or FQDN does not work. However if the remote computer is NOT domain joined FQDN works!

*Also when connecting to windows server 2008/2008 R2, Start Menu and other menus and buttons are black.

All this works with an old freerdp client I found on my hard drive of unknown version from 2016. 

Thank you!

**Comment by haklin0816** [comment]
Thank you, will try the "/gdi:sw" later!
Versions tested:
version 2.0.0-dev2 (68c4bab68) NOT WORKING - built by me
version 2.0.0-dev2 (807fe0413) NOT WORKING - from https://ci.freerdp.com/job/freerdp-nightly-windows/arch=win32,label=vs2013/

Output using FQDN:
[17:13:37:323] [6720:000022cc] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[17:13:37:355] [6720:000022cc] [INFO][com.freerdp.client.windows] - Certificate details:
[17:13:37:355] [6720:000022cc] [INFO][com.freerdp.client.windows] - 	CommonName:<CORRECT_FQDN>
[17:13:37:355] [6720:000022cc] [INFO][com.freerdp.client.windows] - 	Subject: CN = <CORRECT_FQDN>
[17:13:37:355] [6720:000022cc] [INFO][com.freerdp.client.windows] - 	Issuer: CN = <CORRECT_FQDN>
[17:13:37:355] [6720:000022cc] [INFO][com.freerdp.client.windows] - 	Thumbprint: 9a:63:08:b6:60:4f:4f:8b:25:93:2a:ca:2e:6a:df:95:41:b1:ff:7a
[17:13:37:355] [6720:000022cc] [INFO][com.freerdp.client.windows] - 	HostMismatch: Yes
[17:13:37:355] [6720:000022cc] [INFO][com.freerdp.client.windows] - The above X.509 certificate could not be verified, possibly because you do not have the CA certificate in your certificate store, or the certificate has expired. Please look at the OpenSSL documentation on how to add a private CA to the store.

**Comment by akallabeth** [comment]
looks like you need to accept the certificate `/cert-tofu` or `/cert-ignore` come to mind.

**Comment by haklin0816** [comment]
Sorry, missed that when testing, but always use /cert-ignore usually. 
When adding /cert-ignore the output with version 2.0.0-dev2 (55973288f) From WS 2012 R2 the output is.
Using FQDN:
[08:35:43:774] [3976:000010fc] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
Using IP:
[08:34:24:942] [1984:00000edc] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[08:34:32:623] [1984:00000edc] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[08:34:32:623] [1984:00000edc] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16

Both fail...

**Comment by haklin0816** [comment]
By the way /gdi:sw solved the issue with "black menus", Thanks a lot!

**Comment by akallabeth** [comment]
@haklin0816 Looks like our nigthly builds use a very old OpenSSL (see #4525) This should be resolved soon, for the time being you have to compile yourself using a newer version.

**Comment by haklin0816** [comment]
I still cannot connect any rdp sessions from Windows server 2012 or 2016! This wotks with version

...
[20:36:54:772] [4692:00000264] [DEBUG][com.freerdp.core.gcc] - Server rdp encryption method: NONE
[20:36:55:100] [4692:00000264] [DEBUG][com.freerdp.core.rdp] - recv Synchronize Data PDU (0x1F), length: 22
[20:36:55:100] [4692:00000264] [DEBUG][com.freerdp.core.rdp] - recv Control Data PDU (0x14), length: 26
[20:36:55:100] [4692:00000264] [DEBUG][com.freerdp.core.rdp] - recv Control Data PDU (0x14), length: 26
[20:36:55:100] [4692:00000264] [DEBUG][com.freerdp.core.rdp] - recv Font Map Data PDU (0x28), length: 26
[20:36:55:100] [4692:00000264] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[20:36:55:100] [4692:00000264] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[20:36:55:115] [4692:00000264] [DEBUG][com.freerdp.client.windows] - **Main thread exited with 131075**
[20:36:55:115] [4692:00001274] [DEBUG][com.freerdp.client.windows] - Keyboard thread exited.

And... then... nothing... :(

**Comment by akallabeth** [comment]
You're missing the stderr output, add a 2>&1 at the end.

**Comment by haklin0816** [comment]
The output is the same using  "... 2>&1 > file" and "... >file"... ?

**Comment by gramali** [comment]
wfeerdp commandline (wfreerdp.exe /v:machine01 /u:rdpuser /d:domainname /p:secret /cert-ignore /gdi:sw /log-level:TRACE > log.log) is not working from window 2012r2. Please find below the log for the reference.

I am using the latest stable build # 620 from https://ci.freerdp.com/job/freerdp-nightly-windows/arch=win64,label=vs2013/



[07:01:19:551] [11860:0000345c] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[07:01:19:551] [11860:0000345c] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[07:01:19:551] [11860:0000345c] [DEBUG][com.freerdp.channels.cliprdr.client] - VirtualChannelEntryEx
[07:01:19:551] [11860:0000345c] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[07:01:19:566] [11860:0000345c] [DEBUG][com.freerdp.client.windows] - Main thread exited with 0
[07:01:19:566] [11860:000044e4] [DEBUG][com.freerdp.client.windows] - Keyboard thread exited.

**Comment by akallabeth** [comment]
@gramali you're not redirecting error messages, and from my local test this command line is working to my test machines.
Might be a simple issue with DNS not resolvable or user not allowed

**Comment by gramali** [comment]
@akallabeth thank you for your reply. same command working fine for me as well from my laptop windows 10 64 bit.  But not working from any server with windows 2012 R2. I am able to connect the machine from windows 2012 R2 server using MSTSC with same hostname and username. So no issue with DNS and user account. I believe /log-level:TRACE > log.log will log all the message (Trace, Debug, Error, Warn). Please help to resolve this.

**Comment by akallabeth** [comment]
@gramali no, the redirektion skips the errors (or do you see one in your log?)

**Comment by gramali** [comment]
@akallabeth, I don't see any errors in the log. same command working fine in windows 10 and window server 2016. will older build of wreerdp.exe work. where can I download older versions of wreerdp.exe

**Comment by akallabeth** [comment]
That is what I am trying to tell you, you only redirect stdout to the file, NOT stderr which is where errors are written to....

**Comment by gramali** [comment]
@akallabeth Please find below stderr thrown in my windows 2012 R2

[17:14:56:022] [9184:000010e8] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_PASSWORD_CERTAINLY_EXPIRED [0x0002000F]
[17:14:56:022] [9184:000010e8] [ERROR][com.freerdp.core.transport] - BIO_read returned an error: error:14094438:SSL routines:SSL3_READ_BYTES:tlsv1 alert internal error

**Comment by akallabeth** [comment]
Looks like a kerberos/domain related error.
Kerberos support is currently not very reliable :/

**Comment by gramali** [comment]
I am using wfreerdp latest build and not working in windows 2012 R2. pls find the command and logs (STDOUT, STDERR). pls help to resolve this.

1. wfreerdp.exe /v:machinename /u:user01 /d:domainname /p:secret /cert-ignore /gdi:sw /log-level:TRACE > STDOUT.log

2. wfreerdp.exe /v:machinename /u:user01 /d:domainname /p:secret /cert-ignore /gdi:sw /log-level:TRACE 2> STDERR.log

[STDOUT.log](https://github.com/FreeRDP/FreeRDP/files/3157844/STDOUT.log)
[STDERR.log](https://github.com/FreeRDP/FreeRDP/files/3157845/STDERR.log)

**Comment by akallabeth** [comment]
@gramali please test with our builds (recent ones ;)) the debug messages suggest you either have a custom build or a very old one. Attach `wfreerdp.exe /buildconfig` so we know what exactly you're using.

**Comment by gramali** [comment]
@akallabeth sorry the logs posted in the previous when using the wfreerdp 1.1 version. pls find attached logs (STDOUT, STDERR) while tested with latest wfreerdp. 

[stderr.log](https://github.com/FreeRDP/FreeRDP/files/3160814/stderr.log)
[stdout.log](https://github.com/FreeRDP/FreeRDP/files/3160815/stdout.log)

**Comment by gramali** [comment]
@akallabeth can you help on how to recompile with OpenH264 support for windows and how to create commandline interface single wfreerdp.exe.

**Comment by gramali** [comment]
I am trying to recompile with OPENH264 support. I am getting error message "Could NOT find OpenH264 (missing: OPENH264_LIBRARY OPENH264_INCLUDE_DIR)". Please find attached cmk

Cmake Command
c:\GitProjects>cmake -DWITH_OPENH264=ON -DBUILD_SHARED_LIBS=OFF -S . -B C:\GitProjects\FreeRDPBuild\

Cmake Logs
[CMakeError.log](https://github.com/FreeRDP/FreeRDP/files/3166459/CMakeError.log)
[CMakeOutput.log](https://github.com/FreeRDP/FreeRDP/files/3166460/CMakeOutput.log)

**Comment by gramali** [comment]
Now I am able to compile using below command. But when I MSBUILD  throws error C:\GitProjects\FreeRDP\libfreerdp\codec\h264_openh264.c(29): fatal error C1083: Cannot open include file: 'wels/codec_def.h': No such file or directory [c:\GitProjects\FreeRDPBuild\libfreerdp\free
rdp.vcxproj]. Can you someone help on this. 

C:\GitProjects\FreeRDPBuild>cmake -DWITH_OPENH264=ON -DOPENH264_LIBRARY=C:\GitProjects\OpenH264\opwi
n32\openh264-1.8.0-win32.dll -DOPENH264_INCLUDE_DIR=C:\GitProjects\OpenH264\opwin32\ -DBUILD_SHARED_
LIBS=OFF -S . -B C:\GitProjects\FreeRDPBuild\

**Comment by gramali** [comment]
I solved by installing media foundation feature in the server (Add Features/Roles). But I could not recompile with OPENH264 support.
