### ISSUE TITLE
Unable to build FreeRDP server on Windows

### ISSUE THREAD

**Issue by gabriel-sztejnworcel** [FreeRDP/FreeRDP#5000]
Hi,

I would like to build FreeRDP server for Windows. The build instructions that appear in GitHub seem to be only for the client, running cmake will generate Visual Studio projects for the libraries and client, but not for the server. I tried creating the Visual Studio project by myself and adding the source files, and after settings all the include paths, I'm still getting compilation errors (screenshot attached). I checked the sources and it seems like the SURFACE_BITS_COMMAND was changed but the server code was not updated - I'm using FreeRDP-2.0.0-rc3). Is the server code broken? Or am I doing something wrong?

What's the best way for doing this? And generally, I didn't find documentation regarding the FreeRDP server, is there a list of supported features? Would you use it in a production environment?

Thanks,
Gabriel

![image](https://user-images.githubusercontent.com/4405244/48303139-4209aa80-e50f-11e8-8767-0c3c8b9cbf8c.png)

**Comment by akallabeth** [comment]
The library itself is quite complete (and we're working on hardening it further) but the (windows) server components are not.

**Comment by gabriel-sztejnworcel** [comment]
Thanks for the reply.
Does this mean that it's impossible to build FreeRDP server for Windows at the moment?

**Comment by akallabeth** [comment]
Most likely it needs some love.
Might give current `master` a try, we're in a hardening phase trying to fix remaining issues for 2.0, so it might have been fixed.

**Comment by akallabeth** [comment]
@gabriel-sztejnworcel I've pushed some fixes in https://github.com/akallabeth/FreeRDP/tree/dsp_audio_server_api
This should bring windows server back to being compilable.

**Comment by akallabeth** [comment]
Created #5016 to allow compilation again.

**Comment by gabriel-sztejnworcel** [comment]
Hi @akallabeth,
Thanks for your help!

I'm still getting the same errors. Did you commit your changes? I've tried with the current master.

Thanks,
Gabriel

**Comment by akallabeth** [comment]
@gabriel-sztejnworcel it is still a pull request ;)
