### ISSUE TITLE
Latest nightly build (> 20181110) segfaults

### ISSUE THREAD

**Issue by Olen** [FreeRDP/FreeRDP#5017]
**Describe the bug**
Have been testing the nightly builds for some days, and for some reason, all builds after 20181110 segfaults.

**To Reproduce**
1. /opt/freerdp-nightly/bin/xfreerdp $HOME/.config/rdp/server.rdp /u:username

**Expected behavior**
Should be able to connect to the server

**Screenshots**
When running with /log-level:trace I get the following:

[13:39:46:999] [27317:27318] [DEBUG][com.freerdp.core.redirection] - TargetNetAddressesCount: 1
[13:39:46:999] [27317:27318] [DEBUG][com.freerdp.core.redirection] - TargetNetAddresses[0]: 10.0.26.138
 <unfinished ...>) = ?
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

** Application details
* Version of FreeRDP
freerdp-nightly-2.0-0+0~20181115033816.537~1.git268a2c0cf.x86_64

* Command line used
/opt/freerdp-nightly/bin/xfreerdp $HOME/.config/rdp/server.rdp /u:username

* output of `/buildconfig`
This is FreeRDP version 2.0.0-dev4 (268a2c0cf)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=FALSE WITH_FFMPEG=FALSE WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=ON WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 8.2.1
Target architecture: x64

* OS version connecting to
Unknown

_Thank you for reporting a bug!_

**Comment by akallabeth** [comment]
@Olen Thank you for the report, but without your server setup (os, gateway, session redirection?) and content of the RDP file (without passwords and such) it is hard to track.

**Comment by akallabeth** [comment]
Would also suggest to install the debug symbols (`-dbg` or similar, depends on your os) to get (some) useful stack traces

**Comment by akallabeth** [comment]
If you're using a gateway, please wait until #4964 is merged and retry.

**Comment by Olen** [comment]
Hi,

I understand that, however, I have no control over the server (it is a hosted environoment that I am not in charge of).

The reason I have been testing nightly builds is the problem with NLA that has been discussed in other threads.  Builds up to 20181110 did not segfault, but fails with the error
[14:06:26:823] [31788:31792] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[14:06:26:823] [31788:31792] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure

And as I don't control the servers, I can't modify the authentication algorithms on the server...

I will try to get some more debug-info out of either the server or the client...

**Comment by akallabeth** [comment]
@Olen ok, then I hope this one is fixed tomorrow.

**Comment by Olen** [comment]
I can confirm that the latest nightly has fixed the segfault.

However, I am still unable to log in to our rig with all new releases.  

I can successfully log in with
freerdp-2.0.0-41.20180405gita9ecd6a (Fedora 28)

But any later release will error out with 
[09:34:28:441] [9727:9729] [TRACE][com.freerdp.core.gateway.ntlm] - InitializeSecurityContext status SEC_I_CONTINUE_NEEDED [0x00090312]
[09:34:28:446] [9727:9729] [TRACE][com.freerdp.core.gateway.ntlm] - InitializeSecurityContext status SEC_I_COMPLETE_NEEDED [0x00090313]
[09:34:28:452] [9727:9729] [DEBUG][com.freerdp.core.gateway.rdg] - RDG_IN_DATA authorization result: 200
[09:34:28:456] [9727:9729] [DEBUG][com.freerdp.core.gateway.rdg] - Handshake response received
[09:34:28:461] [9727:9729] [DEBUG][com.freerdp.core.gateway.rdg] - Tunnel response received
[09:34:29:561] [9727:9729] [DEBUG][com.freerdp.core.gateway.rdg] - Tunnel authorization received
[09:34:29:565] [9727:9729] [DEBUG][com.freerdp.core.gateway.rdg] - Channel response received
[09:34:29:565] [9727:9729] [DEBUG][com.freerdp.core.gateway.rdg] - Channel error 800759da
[09:34:29:565] [9727:9729] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[09:34:29:566] [9727:9729] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]
[09:34:29:566] [9727:9729] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[09:34:29:566] [9727:9729] [DEBUG][com.freerdp.core.transport] - transport_check_fds: transport_read_pdu() - -1
[09:34:29:566] [9727:9729] [DEBUG][com.freerdp.core.rdp] - transport_check_fds() - -1

**Comment by mfleisz** [comment]
@Olen this seems to be the same issue as mentioned in https://github.com/FreeRDP/FreeRDP/issues/4663#issuecomment-390757649

**Comment by akallabeth** [comment]
Closing this as the segfault is resolved.
As for the connection issue, this is a server response (`E_PROXY_RAP_ACCESSDENIED` if I'm not mistaken) and therefore a configuration / setup issue.
Might need some better logging in gateway code.
If you're also using a broker setup behind the gateway, #4875 might be your issue.
