### ISSUE TITLE
USB redirection "not exist in udevman"

### ISSUE THREAD

**Issue by Jackson-256** [FreeRDP/FreeRDP#5702]
I tried to redirect my webcam through the usb redirection with running the cmdline 
\# "xfreerdp /p:*** /v:*** /u:*** /usb:id,dev:18ec:3399"
but got these log

- [02:21:52:645] [2583:2584] [ERROR][com.winpr.commandline] - Failed at index 1 [id]: **Unexpected keyword**
- [02:21:52:645] [2583:2584] [ERROR][com.freerdp.channels.urbdrc.client] - error processing arguments
- [02:21:52:646] [2583:2590] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded fake backend for rdpsnd
- [02:21:52:651] [2583:2584] [WARN][com.freerdp.channels.urbdrc.client] - udevman_get_udevice_by_addr
- [02:21:52:651] [2583:2584] [WARN][com.freerdp.channels.urbdrc.client] - bus:0 dev:0 not exist in udevman
- [02:21:52:651] [2583:2584] [INFO][com.freerdp.channels.urbdrc.client] - VID: 0x18EC, PID: 0x3399
- [02:21:52:721] [2583:2584] [WARN][com.freerdp.channels.urbdrc.client] - udevman_get_udevice_by_addr
- [02:21:52:721] [2583:2584] [WARN][com.freerdp.channels.urbdrc.client] - bus:3 dev:4 not exist in udevman

lsusb
.....
- Bus 003 Device 004: ID 18ec:3399 Arkmicro Technologies Inc. 
- Bus 003 Device 002: ID 0bda:5411 Realtek Semiconductor Corp. 
- Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Is there any something wrong ?
and I run it as root.

**Comment by akallabeth** [comment]
Yes the messages are misleading.
does it work though? (might take some time, on my test machine it takes ~20 seconds before the device is available server side)

**Comment by akallabeth** [comment]
oh, and which version are you using? get different messages on current master (less misleading, still not perfekt)

**Comment by akallabeth** [comment]
oh, and is it enabled server side? https://stackoverflow.com/questions/33719489/how-to-enable-usb-redirection-in-windows-10 has some hints on what there is to do.

**Comment by Jackson-256** [comment]
@akallabeth It seemed like the client side couldn't handle the usb device.
- bus:3 dev:4 not exist in udevman

**Comment by Jackson-256** [comment]
@akallabeth the version of client is the current master

**Comment by akallabeth** [comment]
@Jackson-256 no, the client side can handle it (the messages are, as mentioned, misleading)

**Comment by Jackson-256** [comment]
@akallabeth btw, is it possible to support the usb redirection on shadow instead of the native remote desktop on windows

**Comment by akallabeth** [comment]
@Jackson-256 well, no server side support is implemented, so yes, it would be possible if someone implements it ;)

**Comment by Jackson-256** [comment]
@akallabeth oh, I see , sadness, my remote host is win10 and it doesn't work! :(, but the drive redirection work

**Comment by akallabeth** [comment]
@Jackson-256 you know that some device classes are forbidden by windows to be redirected?

**Comment by Jackson-256** [comment]
@akallabeth such as ?

**Comment by akallabeth** [comment]
Mass storage and such. The server will not accept such devices.

**Comment by Jackson-256** [comment]
@akallabeth I just want to redirect my usb webcam and see if it work normally.. anyway

**Comment by akallabeth** [comment]
that I can do with current master (`Logitech, Inc. HD Pro Webcam C920`) but it is quite fragile (even when redirecting with mstsc, need to logout/reboot the server session sometimes)

**Comment by Jackson-256** [comment]
@akallabeth as you mentioned , it's also not possible to redirect usb device to the server side on  linux, it only work for the native rdp on windows! ?

**Comment by akallabeth** [comment]
yes, that is correct. the server side is currently not implemented (would require a linux kernel driver that can emulate the usb device in question, so maybe something with the gadet drivers is possible)

**Comment by Jackson-256** [comment]
@akallabeth it seems there are a lot work to do, but you guys really do a great job.

**Comment by Jackson-256** [comment]
@akallabeth Hi, do you have any ideas for supporting usb redirection on windows yet? I just know there is one way using usbdk and spice but that is for VDI.

**Comment by akallabeth** [comment]
Fixed with #5745

**Comment by Fantu** [comment]
@akallabeth  thanks for your big work on urbdrc, you marked this fixed but seems still present on my latest test.
I'm trying with freerdp2 2.2.0...
```
xfreerdp /u:fabio /v:192.168.178.50 /usb:dbg,dev:04f2:b521 /log-filter:com.freerdp.channel.urbdrc.client:DEBUG
loading channel drdynvc
connected to 192.168.178.50:3389
Password: 
Loading Dynamic Virtual Channel urbdrc
udevman_get_udevice_by_addr: bus:0 dev:0 not exist in udevman
VID: 0x04F2 PID: 0xB521
  Port: 4
  DevPath: 1-1.4
  Hub BUS/DEV: 1 2
udev_get_hub_handle: libusb_open success!
Regist Device: Vid: 0x04F2 Pid: 0xB521 InterfaceClass = 0xE
udevman_get_udevice_by_addr: bus:1 dev:5 not exist in udevman
```
and still give "not exist in udevman" and I not see the device in windows, I also tried with other usb device, I already changed udev rules about usb (for avoid libusb open error before) and in windows remotefx usb redirection in group policy is enabled

from lsusb...
`Bus 001 Device 005: ID 04f2:b521`

there are these that seems strange to me:
```
  Port: 4
  DevPath: 1-1.4
  Hub BUS/DEV: 1 2
```
and trying with "/usb:dbg,addr:01:05" hang on connect after "Password" with xfreerdp max cpu usage and no urbdrc log visible, I also waited 3-4 minutes before kill the process

with "/usb:dbg,addr:001:005" and "/usb:dbg,addr:1:5" connect successful but no output after "Loading Dynamic Virtual Channel urbdrc" line and device not visible on remote


a rebuild of freerdp including latest urbdrc fixes (https://github.com/FreeRDP/FreeRDP/commits/master/channels/urbdrc) is needed or is there something else I'm missing?

thanks for any reply and sorry for my bad english
