### ISSUE TITLE
Unable to minimize remoteapp window. 

### ISSUE THREAD

**Issue by akklaw** [FreeRDP/FreeRDP#6014]
Launch MS word as remoteapp.  Client minimize icon on the upper right corner of MS word window.  Expect to minimize windows.  Actual: MS word flashes screen one time and window stays on display.  If I use the linux menu from taskbar, minimize function works.

1) Using remoteapp /app option to launch MS word
2) click minimize icon on the upper right corner of MS word window

Expected:
MS word window should minimize, actual: window stay on display and there is a flashing on the MS word window one time.  This seems to be the windows takes the action to minimize and then it un-minimizes.

**Application details**
* Version of FreeRDP - Master branch as of 3/31/2020
* Command line used - client/X11/xfreerdp /u:<user> /p:<PWD> /v:<host ip> /cert-ignore /app:'C:\Program Files (x86)\Microsoft Office\Office16\WINWORD.exe'

* OS version connecting to - windows server 2016
 
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - RHEL 7.6
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] RHEL 7.6

**Comment by akklaw** [comment]
Update: With latest master branch as of 3/31/2020, the minimize menu in the taskbar is no longer working.

**Comment by roland65** [comment]
Hi, same issue with Ubuntu 20.04 and freerdp 2.1.1.

**Comment by ganeshjkale** [comment]
@akallabeth Issue persists with Freerdp v2.2.0 .

Issue reproducible on below OS:-
Xubuntu-16.04,18.04,20.04

Issue not reproducible in below OS:-
Ubuntu 16.04 (unity)

Workaround:-
Maximize  then minimize remote app is working

Note:-
1:-Xubuntu Win+D to minimize all app is also not working on remote app.

**Comment by roland65** [comment]
I can confirm this issue appears within XFCE4 desktop but not with GNOME desktop.

Here is a patch against freerdp 2.2.0 that fixes the bug in XFCE and also works with GNOME. I tested it in Ubuntu 20.04.§
[xfce4.patch.gz](https://github.com/FreeRDP/FreeRDP/files/5754308/xfce4.patch.gz)

**Comment by voltumna** [comment]
I am using xfreerdp and the patch is not finding the file to patch,
does it matter that I had to install freerdp2-x11
I tried to find the file that it tries to patch but I cannot find any
Thanks

**Comment by akallabeth** [comment]
@roland65 ok, did miss the patch, better submit a pull request, these I can´t miss ;)

**Comment by voltumna** [comment]
OOooo silly me!

**Comment by akallabeth** [comment]
@roland65 @voltumna I´ve created #6823 which should address the issues during state change. please test and tell if it works.

**Comment by rbreaves** [comment]
To note - this fix would have made it into 2.3.0. The ubuntu 18.04 repo still references 2.2.0 as of today.

**Comment by rbreaves** [comment]
Just test on 2.3.2 and with XFCE, plank,  xfwm4 version 4.12.4, ubuntu 18.04 (galliumOS 3.1) and this ppa remmina-ppa-team/remmina-next-daily it still fails to minimize apps initialized via remoteapp. Please re-open this issue ticket.

**Comment by akallabeth** [comment]
@rbreaves is it fixed on master? If you want a backport then please create a pull request with `git cherry-pick -x <commit>` against stable-2.0 branch.

**Comment by rbreaves** [comment]
I’ll have to try this a bit later if I need to compile it myself. I was just trying the latest in that PPA & assume the fix was merged there already, but perhaps not for 18.04?

Atm I’m just dropping remoteapp & fullscreening the app I need. Need to figure out how to set the default theme for remoteapps any ways.

**Comment by bo0ohXae** [comment]
Bug still exists in debian/stable (bullseye) freerdp2-x11 version 2.3.0+dfsg1-2+deb11u1 AND in bullseye-backparts which has  freerdp2-x11 version 2.7.0+dfsg1-1~bpo11+1
