### ISSUE TITLE
Since 2.1.1+dfsg1-0ubuntu0.20.04.1 update, Window7 connection disconnect

### ISSUE THREAD

**Issue by olivier-morin** [FreeRDP/FreeRDP#6258]
With Apache Guacamole  installed on a Ubuntu 20.04, since last update, connection to Windows 7 or 2008R2 are disconnected every few seconds.

Start-Date: 2020-06-02  06:46:06
Commandline: /usr/bin/unattended-upgrade
Upgrade: libwinpr-tools2-2:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), libwinpr2-dev:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), libwinpr2-2:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), libfreerdp-server2-2:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), libfreerdp-shadow-subsystem2-2:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), libfreerdp2-2:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), freerdp2-dev:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), libfreerdp-shadow2-2:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), libfreerdp-client2-2:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), winpr-utils:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1)
End-Date: 2020-06-02  06:46:08

**Comment by akallabeth** [comment]
@olivier-morin any logs?

**Comment by olivier-morin** [comment]
Ok, how can i generate logs for freerdp in guacamole ?

**Comment by akallabeth** [comment]
@olivier-morin well, I don´t know. You could give me a short install instruction to reproduce your setup, maybe that is sufficient.

**Comment by emeygret** [comment]
Hello, I have the same pb, only on Windows 7, here is syslog. 
I can see that I can connect on workstation if no windows are open on desktop, but if I clic on start menu I was disconnected. some windows could be open but other not if the windows is minimized no problem but when you restore it session is disconnected like you clic on start menu... hope theses informations will help...

`Jun  3 20:28:52 guacamoleServer guacd[6039]: Connected to RDPDR 1.12 as client 0x0002
Jun  3 20:28:52 guacamoleServer guacd[957]: guacd[6039]: INFO:#011Connected to RDPDR 1.12 as client 0x0002
Jun  3 20:28:52 guacamoleServer guacd[6039]: RDPDR user logged on
Jun  3 20:28:52 guacamoleServer guacd[957]: guacd[6039]: INFO:#011RDPDR user logged on
Jun  3 20:28:52 guacamoleServer guacd[6039]: Connection closed.
Jun  3 20:28:52 guacamoleServer guacd[957]: guacd[6039]: ERROR:#011Connection closed.
Jun  3 20:28:52 guacamoleServer guacd[6039]: Internal RDP client disconnected
Jun  3 20:28:52 guacamoleServer guacd[957]: guacd[6039]: INFO:#011Internal RDP client disconnected
Jun  3 20:28:52 guacamoleServer guacd[6039]: User "@c20a66c5-c1e2-4516-b360-6254567f4986" disconnected (0 users remain)
Jun  3 20:28:52 guacamoleServer guacd[957]: guacd[6039]: INFO:#011User "@c20a66c5-c1e2-4516-b360-6254567f4986" disconnected (0 users remain)
Jun  3 20:28:52 guacamoleServer guacd[957]: guacd[6039]: INFO:#011Last user of connection "$2bec2d1a-5cc2-4be9-a9a5-02e3b83754a2" disconnected
Jun  3 20:28:52 guacamoleServer guacd[6039]: Last user of connection "$2bec2d1a-5cc2-4be9-a9a5-02e3b83754a2" disconnected
Jun  3 20:28:52 guacamoleServer guacd[957]: Connection "$2bec2d1a-5cc2-4be9-a9a5-02e3b83754a2" removed.
Jun  3 20:28:52 guacamoleServer guacd[957]: guacd[957]: INFO:#011Connection "$2bec2d1a-5cc2-4be9-a9a5-02e3b83754a2" removed.
Jun  3 20:28:52 guacamoleServer tomcat9[2294]: 20:28:52.860 [Thread-189] INFO  o.a.g.tunnel.TunnelRequestService - User "myuser" disconnected from connection "DEFAULT". Duration: 4607 milliseconds
Jun  3 20:28:52 guacamoleServer tomcat9[2294]: 20:28:52.860 [Thread-189] DEBUG o.a.g.net.InetGuacamoleSocket - Closing socket to guacd.
Jun  3 20:28:52 guacamoleServer tomcat9[2294]: 20:28:52.887 [https-openssl-nio-8443-exec-10] DEBUG o.a.g.w.GuacamoleWebSocketTunnelEndpoint - Connection to guacd closed.
Jun  3 20:28:52 guacamoleServer tomcat9[2294]: org.apache.guacamole.GuacamoleConnectionClosedException: Connection to guacd is closed.
`

**Comment by javiers** [comment]
Same issue here. I have desktops with Windows 7/ Windows 2008 Server R2, and the server is running Ubuntu 18.04 with guacamole-server (guacd) 1.1.0 manually compiled, with libfreerdp2-2 (2.1.1+dfsg1-0ubuntu0.18.04.1). When the user makes some action (as clicking the Start menu or browsing the local network), the RDP session is closed and the user is disconnected. Downgrading libfreerdp2-2 to the version previously installed (2.0.0\~git202003120736-0+remmina202003121121.r3b673be.d287a1e7~ubuntu18.04.1) solves the problem. 

The following are sample log entries for a desktop running Windows 7.

tomcat log:

11:42:24.726 [http-nio-8080-exec-41] INFO  o.a.g.tunnel.TunnelRequestService - User "userxxx" connected to connection "291".
11:42:59.610 [http-nio-8080-exec-19] INFO  o.a.g.tunnel.TunnelRequestService - User "userxxx" disconnected from connection "291". Duration: 34883 milliseconds

guacd log: 

11:42:24 guacd[999]: Processing instruction: size
11:42:24 guacd[999]: Processing instruction: audio
11:42:24 guacd[999]: Processing instruction: video
11:42:24 guacd[999]: Processing instruction: image
11:42:24 guacd[999]: Processing instruction: timezone
11:42:24 guacd[999]: Parameter "console" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "console-audio" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "disable-auth" omitted. Using default value of 0.
11:42:24 guacd[999]: No security mode specified. Defaulting to security mode negotiation with server.
11:42:24 guacd[999]: Parameter "port" omitted. Using default value of 3389.
11:42:24 guacd[999]: User resolution is 1366x657 at 96 DPI
11:42:24 guacd[999]: Parameter "dpi" omitted. Using default value of 96.
11:42:24 guacd[999]: Using resolution of 1364x657 at 96 DPI
11:42:24 guacd[999]: Parameter "read-only" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "client-name" omitted. Using default value of "Guacamole RDP".
11:42:24 guacd[999]: Parameter "enable-wallpaper" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "enable-theming" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "enable-font-smoothing" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "enable-full-window-drag" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "enable-desktop-composition" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "enable-menu-animations" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "disable-bitmap-caching" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "disable-offscreen-caching" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "disable-glyph-caching" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "color-depth" omitted. Using default value of 16.
11:42:24 guacd[999]: Parameter "disable-audio" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "enable-printing" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "printer-name" omitted. Using default value of "Guacamole Printer".
11:42:24 guacd[999]: Parameter "enable-drive" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "drive-name" omitted. Using default value of "Guacamole Filesystem".
11:42:24 guacd[999]: Parameter "drive-path" omitted. Using default value of "".
11:42:24 guacd[999]: Parameter "create-drive-path" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "timezone" omitted. Using default value of "America/Buenos_Aires".
11:42:24 guacd[999]: Parameter "enable-sftp" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "sftp-hostname" omitted. Using default value of "HOSTXXX".
11:42:24 guacd[999]: Parameter "sftp-port" omitted. Using default value of "22".
11:42:24 guacd[999]: Parameter "sftp-username" omitted. Using default value of "".
11:42:24 guacd[999]: Parameter "sftp-password" omitted. Using default value of "".
11:42:24 guacd[999]: Parameter "sftp-passphrase" omitted. Using default value of "".
11:42:24 guacd[999]: Parameter "sftp-root-directory" omitted. Using default value of "/".
11:42:24 guacd[999]: Parameter "sftp-server-alive-interval" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "recording-name" omitted. Using default value of "recording".
11:42:24 guacd[999]: Parameter "recording-exclude-output" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "recording-exclude-mouse" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "recording-include-keys" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "create-recording-path" omitted. Using default value of 0.
11:42:24 guacd[999]: Resize method: none
11:42:24 guacd[999]: Parameter "enable-audio-input" omitted. Using default value of 0.
11:42:24 guacd[999]: Parameter "gateway-port" omitted. Using default value of 443.
11:42:24 guacd[999]: User "@xxxxxxxxxx-xxxxx-xxxxx-xxxx-xxxxxxxxxxxx" joined connection "$xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" (1 users now present)
11:42:24 guacd[999]: Client is using protocol version "VERSION_1_1_0"
11:42:24 guacd[999]: Loading keymap "base"
11:42:24 guacd[999]: Loading keymap "en-us-qwerty"
11:42:24 guacd[999]: freerdp_connect:freerdp_set_last_error_ex resetting error state
11:42:24 guacd[999]: Support for CLIPRDR (clipboard redirection) registered. Awaiting channel connection.
11:42:24 guacd[999]: Support for static channel "rdpdr" loaded.
11:42:24 guacd[999]: Support for static channel "rdpsnd" loaded.
11:42:24 guacd[999]: Local framebuffer format  PIXEL_FORMAT_BGRX32
11:42:24 guacd[999]: Remote framebuffer format PIXEL_FORMAT_RGB16
11:42:25 guacd[999]: primitives autodetect, using optimized
11:42:25 guacd[999]: freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
11:42:25 guacd[999]: freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
11:42:25 guacd[999]: Unable to find a match for unix timezone: America/Argentina/Buenos_Aires
11:42:25 guacd[999]: CLIPRDR (clipboard redirection) channel connected.
11:42:25 guacd[999]: SVC "rdpdr" connected.
11:42:25 guacd[999]: SVC "rdpsnd" connected.
11:42:26 guacd[999]: Connected to RDPDR 1.12 as client 0x0003
11:42:26 guacd[999]: Ignoring server capability set type=0x0001, length=44
11:42:26 guacd[999]: Ignoring server capability set type=0x0002, length=8
11:42:26 guacd[999]: Ignoring server capability set type=0x0003, length=8
11:42:26 guacd[999]: Ignoring server capability set type=0x0004, length=8
11:42:26 guacd[999]: Ignoring server capability set type=0x0005, length=8
11:42:26 guacd[999]: Sending capabilities...
11:42:26 guacd[999]: Capabilities sent.
11:42:26 guacd[999]: Client ID confirmed
11:42:26 guacd[999]: Clipboard data received. Reporting availability of clipboard data to RDP server.
11:42:26 guacd[999]: [cliprdr_packet_format_list_new] called with invalid type 00000000
11:42:26 guacd[999]: Clipboard data received. Reporting availability of clipboard data to RDP server.
11:42:26 guacd[999]: [cliprdr_packet_format_list_new] called with invalid type 00000000
11:42:57 guacd[999]: rdp_set_error_info:freerdp_set_last_error_ex resetting error state
11:42:57 guacd[999]: ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off their session on the server.
11:42:57 guacd[999]: rdp_set_error_info:freerdp_set_last_error_ex ERRINFO_LOGOFF_BY_USER [0x0001000C]
11:42:57 guacd[999]: rdp_recv_tpkt_pdu: rdp_recv_deactivate_all() fail
11:42:57 guacd[999]: transport_check_fds: transport->ReceiveCallback() - -1
11:42:57 guacd[999]: RDP server closed connection: Manually logged off.
11:42:57 guacd[999]: Disconnect reason code: 0xC.
11:42:57 guacd[999]: SVC "rdpdr" disconnected.
11:42:57 guacd[999]: SVC "rdpsnd" disconnected.
11:42:57 guacd[999]: Internal RDP client disconnected
11:42:59 guacd[999]: User "@xxxxxxxxxx-xxxxx-xxxxx-xxxx-xxxxxxxxxxxx"disconnected (0 users remain)
11:42:59 guacd[999]: Last user of connection "$xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" disconnected
11:42:59 guacd[999]: Requesting termination of client...
11:42:59 guacd[999]: Client terminated successfully.


Also, in the kern.log I have some occasional segfaults (apparently solved with the downgrade):

10:57:55 guacamole kernel: [394677.038721] guacd[13418]: segfault at 48 ip 00007efe504f0406 sp 00007efdcdfface0 error 4 in libfreerdp2.so.2.1.1[7efe50482000+161000]
11:09:47 guacamole kernel: [395388.672124] guacd[17220]: segfault at 7efdaa4b701c ip 00007efe60132c7b sp 00007efdb9fd2d20 error 4 in libguac-client-rdp.so.0.0.0[7efe6010d000+3b000]
11:43:52 guacamole kernel: [397434.053707] guacd[38623]: segfault at 4 ip 00007efe37d4fb07 sp 00007efda57a13b8 error 4 in libwinpr2.so.2.1.1[7efe37ce5000+f6000]

**Comment by akallabeth** [comment]
@javiers ok, that log is interesting. looks like the session is disconnected on the server end (`ERRINFO_LOGOFF_BY_USER` is a server side disconnect)
As for the segfault, sorry for the inconvenience, we had a resource cleanup order issue with `2.1.1`  that should be fixed with #6259

**Comment by akallabeth** [comment]
@javiers could you try to reproduce with a session using only `xfreerdp`?

**Comment by olivier-morin** [comment]
Bonjour,
On my ubuntu 18.04 server i revert to 2.0.0, i recompile guacd and every ting is now fine.
The solution was here : [http://apache-guacamole-general-user-mailing-list.2363388.n4.nabble.com/Guacamole-FreeRDP-disconnect-td8575.html](url) thanks to "ivanmarcus".

ldconfig -v | grep libfree (show current version)
apt install aptitude (it dealt with dependencies much better)
apt-cache showpkg freerdp2-dev (show packages available)
aptitude install freerdp2-dev=2.0.0~git20170725.1.1648deb+dfsg1-7 (choose and [re]install 2.0.0)
ldconfig -v | grep libfree (check correct package installed)

The other solution is to install a guacd sever proxy with freerdp 2.2.0 to connect on W7 W2008 machines and install freerdp 2.1.1 for secutity on your main guacamole serer.
 This solution is OK and in production at my job.

**Comment by javiers** [comment]
> @javiers could you try to reproduce with a session using only `xfreerdp`?

I've tried to reproduce the error using fresh installed Windows 7 + Ubuntu 18.04, but until now everything works fine. I'll keep trying to adapt the xfreerdp command line parameteres to match the guacd connection ones.

**Comment by akallabeth** [comment]
@javiers I think to get `xfreerdp` `2.1.1` you´ll need to test on `ubuntu 20.04`.
Other option would be to give me a short install how to for the guacamole you´re using so we have matching setups.

**Comment by javiers** [comment]
> @javiers I think to get `xfreerdp` `2.1.1` you´ll need to test on `ubuntu 20.04`.

The version included in Ubuntu 18.04 is 2.1.1 (since 2020-06-01, the upgrade that broke my setup): https://launchpad.net/ubuntu/+source/freerdp2/2.1.1+dfsg1-0ubuntu0.18.04.1

I've installed guacamole 1.1.0 as described in the official docs (https://guacamole.apache.org/doc/gug/), using pre-compiled guacamole-client and manually-compiled guacd server (using FreeRDP 2.0.0~git202003120736-0).

**Comment by olivier-morin** [comment]
Bonsoir,
My production Guacamole server (Ubuntu 20;04) was originaly with the version 2.0.0 of freeRDP and every things was fine, but the 2020-06-02 Ubuntu made an auto update (see logs), and then RDP goes wgrong with W7.

So i tried with my previous Guacamole server (Ubuntu 18.04) and the same bug came after updating freedrp from 2.0.0 to 2.1.1.

So i revert it to 2.0.0 and rerun the script, now it is ok again...

Il use this script to installa Guacamole : [https://github.com/MysticRyuujin/guac-install](url)

Logs of Auto update :





Start-Date: 2020-06-02  06:46:06
Commandline: /usr/bin/unattended-upgrade
Upgrade: libwinpr-tools2-2:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), libwinpr2-dev:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), libwinpr2-2:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), libfreerdp-server2-2:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), libfreerdp-shadow-subsystem2-2:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), libfreerdp2-2:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), freerdp2-dev:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), libfreerdp-shadow2-2:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), libfreerdp-client2-2:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1), winpr-utils:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1)
End-Date: 2020-06-02  06:46:08

Start-Date: 2020-06-02  06:46:12
Commandline: /usr/bin/unattended-upgrade
Upgrade: ca-certificates:amd64 (20190110ubuntu1, 20190110ubuntu1.1)
End-Date: 2020-06-02  06:46:15

Start-Date: 2020-06-02  06:46:18
Commandline: /usr/bin/unattended-upgrade
Upgrade: freerdp2-x11:amd64 (2.0.0~git20190204.1.2693389a+dfsg1-2build2, 2.1.1+dfsg1-0ubuntu0.20.04.1)
End-Date: 2020-06-02  06:46:19

Start-Date: 2020-06-02  06:46:22
Commandline: /usr/bin/unattended-upgrade
Remove: gstreamer1.0-plugins-base:amd64 (1.16.2-4)
End-Date: 2020-06-02  06:46:22

Start-Date: 2020-06-02  06:46:24
Commandline: /usr/bin/unattended-upgrade
Remove: libxv1:amd64 (2:1.0.11-1)
End-Date: 2020-06-02  06:46:24

Start-Date: 2020-06-02  06:46:27
Commandline: /usr/bin/unattended-upgrade
Remove: libcdparanoia0:amd64 (3.10.2+debian-13)
End-Date: 2020-06-02  06:46:27

Start-Date: 2020-06-02  06:46:29
Commandline: /usr/bin/unattended-upgrade
Remove: liborc-0.4-0:amd64 (1:0.4.31-1), libgstreamer-plugins-base1.0-0:amd64 (1.16.2-4)
End-Date: 2020-06-02  06:46:30

Start-Date: 2020-06-02  06:46:32
Commandline: /usr/bin/unattended-upgrade
Remove: libvisual-0.4-0:amd64 (0.4.0-17)
End-Date: 2020-06-02  06:46:32

**Comment by olivier-morin** [comment]
Bonjour,

I've made a fresh full install of an ubuntu 20.04 server an run the guacd script : [https://github.com/MysticRyuujin/guac-install/blob/master/guac-install-server.sh](url)
This script install the last version of freerdp i.e. the 2.1.1.
So the result is still the same, on W7 or WS2008, rdp is deconnected after few seconds or when you click to open a soft.

**Comment by yur7530** [comment]
I am running into the same problem I think but with some weird quirks.
Using guacamole 1.1.0, freerdp 2.1.1 because of MysticRyuujin script on ubuntu 18.04:
1. I cannot rdp to windows 2003 servers unless i set the colors to 16 bit or above.  Definitely not 256 colors.  Else I get server unavailable.
2. When I do connect with other colors, the connections works great until I launch ms word 2003 and when rendering the menus - i get kicked out.  Message is then server unavailable.  Yet for most programs there is no issue.  Excel causes the kick out also.

I could not find anything of value in the logs besides, you got disconnected...

Out of desperation, I reverted back to an older version of Guac with and older freerdp.  Too puzzled by the weird way it disconnects...

Gonna try to make oliver's suggestion and let you know how it goes.

**Comment by olivier-morin** [comment]
Bonjour !

I gonna try a reinstall with Ubuntu 20.04, guacd 1.1.0 but freerdp 2.0.0.
I'll tell you ASAP.

**Comment by olivier-morin** [comment]
Ok, but could you tell me how to find or generate freerpd logs ?

**Comment by yur7530** [comment]
If we are just talking the syslog, guac logs... mine didn't show anything but generic connection dropped messages.   But yeah, I'd be glad to get freerdp logs to you.  I saved one of the attempts in a vm i can spin it back up to look.  Let me know how to generate those logs too.

**Comment by yur7530** [comment]
@olivier-morin I'm gonna try to your changes!  to see if they fix the color issues disconnect I was having.  WIsh me luck and thanks again for sharing!

**Comment by akallabeth** [comment]
@olivier-morin @yur7530 you can get better freerdp logs if you start with environment variable `WLOG_LEVEL=debug` or `trace` set

**Comment by olivier-morin** [comment]
Bonjour,
I would like to test teh 2.1.2 version on ubuntu focal, where to get it ?

**Comment by akallabeth** [comment]
https://ci.freerdp.com/job/freerdp-nightly-binaries/

that should give you latest master

**Comment by akallabeth** [comment]
Any update on this one?

**Comment by olivier-morin** [comment]
Bonjour,

I am wainting for the 2.1.2 ubuntu package update to try a new install from scratch.

**Comment by akallabeth** [comment]
@olivier-morin ok. `2.1.2` sadly has a nasty bug #6299 which was fixed with was fixed with #6300, so check the package has that applied once it arrives.

**Comment by olivier-morin** [comment]
Bonjour,

Still waiting...

**Comment by akallabeth** [comment]
Closing as already fixed with `2.2.0` release.
@olivier-morin 2.2.0 has been released, so build from source or you need to wait for ubuntu to update their packages.

**Comment by javiers** [comment]
Using FreeRDP 2.2.0 (libfreerdp2-2_2.2.0+git202007201338-0+remmina202007220704.rd2ba84a.d97f0237~ubuntu18.04.1_amd64) with guacd 1.2.0 (compiled from source). The bug is still there:

Jul 27 18:40:06 test guacd[867]: invalid bitmap bpp 0
Jul 27 18:40:06 test guacd[867: SECONDARY ORDER [0x00] Cache Bitmap failed
Jul 27 18:40:06 test guacd[867]: order flags 03 failed
Jul 27 18:40:06 test guacd[867]: Fastpath update Orders [0] failed, status 0
Jul 27 18:40:06 test guacd[867]: fastpath_recv_update() - -1
Jul 27 18:40:06 test guacd[867]: fastpath_recv_update_data() fail
Jul 27 18:40:06 test guacd[867]: transport_check_fds: transport->ReceiveCallback() - -3
Jul 27 18:40:06 test guacd[867]: freerdp_check_fds() failed - 0
Jul 27 18:40:06 test guacd[867]: Connection closed.
Jul 27 18:40:06 test guacd[867]: SVC "rdpdr" disconnected.
Jul 27 18:40:06 test guacd[867]: SVC "rdpsnd" disconnected.
Jul 27 18:40:06 test guacd[867]: Internal RDP client disconnected

**Comment by akallabeth** [comment]
@javiers no, that is something different. Run the same thing again with `WLOG_LEVEL=trace` to get a better log and create a new issue with that.

**Comment by takichikawa** [comment]
I troubled Windows2003R2 too.
 but "disable-glyph-caching: true" seems improve it.

**Comment by olivier-morin** [comment]
Bonjour
On Windows 2008R2 and Windows 7 set "Disable glyph caching" to true and it's OK ! with 2.1.1 !

**Comment by javiers** [comment]
Confirmed: setting "Disable glyph caching" eliminates the issue in Windows 2008 R2 and Windows 7.

**Comment by sebthesun** [comment]
Disable glyph caching solve the problem for me too, thanks everyone!

**Comment by joksik** [comment]
i can confirm that bug still exists.
I use arch linux with latest freerdp 2.2.0 and yesterday i download latest guacamole 1.3 from github and compile everything from the beginning. after i connect with guacamole to windows 7 i am disconnect. works with windows 10 and windows server 2016&2019
after i disable glyph caching in guacamole i can connect to windows 7 without disconnecting

**Comment by akallabeth** [comment]
@joksik could you try a build utilizing current master? we fixed a parsing issue recently which could affect this.

**Comment by Coolguy3289** [comment]
Bumping this to confirm this bug still exists on Ubuntu 20.04 with freerdp2-dev, Guacamole 1.3.0, fresh install.

**Comment by bmiklautz** [comment]
@Coolguy3289 @romanad even if you use `disable-glyph-caching: true`?

**Comment by romanad** [comment]
> @Coolguy3289 @romanad even if you use `disable-glyph-caching: true`?

Thank you very much. I disabled it in connection settings in web interface and now everything's fine : )

**Comment by Coolguy3289** [comment]
I did disable glyph caching to fix it, however I would presume this is a workaround, not a fix to the true issue.

**Comment by akallabeth** [comment]
@Coolguy3289 the fix is updating to a newer version of `freerdp` where we actually fixed the glyph-cache ;)
See https://github.com/FreeRDP/FreeRDP/blob/stable-2.0/ChangeLog
