### ISSUE TITLE
macOS smartcard support still has issues

### ISSUE THREAD

**Issue by vscfreire** [FreeRDP/FreeRDP#6821]
**Describe the bug**
Recent pull request #6792 considerably improved smart card usability when using FreeRDP on Linux to connect to a Windows server. It improved performance (no hard data, but things seem to be faster) and [scard-tester](https://github.com/akallabeth/scard-tester), which previously crashed before getting to the end of tests now runs until the end. Overall, the improvements were very positive.

On macOS, which also uses the PCSC backend, there are still some issues. Generally speaking, the pull request seems to have improved performance (smart card access seems quicker). I can identify, however, two odd situations which are easily reproducible. As stated before, these scenarios present no problems when running the client on Linux.

**To Reproduce**
Steps to reproduce the behavior (scenario 1):
1. Connect a smart card reader and insert smart card
2. Connect to a remote windows server (tested with WS 2016) with smart card redirection
3. Run scard-tester on the remote server
4. After a couple of seconds, the RDP session disconnects (before the PR changes, the scard-tester application crashed)

Steps to reproduce the behavior (scenario 2):
1. Connect a smart card reader and insert smart card
2. Connect to a remote windows server (tested with WS 2016) with smart card redirection
3. On the remote server, use the Microsoft Remote Desktop Client (mstsc.exe) to connect to a second Windows Server
4. On the second remote server, use any smart card application
5. The second (mstsc.exe) RDP session hangs/freezes
6. Remove the card from the reader (no need to disconnect the reader)
7. The second (mstsc.exe) RDP resumes and is now working normally

Note that both these scenarios work just fine when running the client on Linux.

**Expected behavior**
Scenario 1: the scard-tester application should run normally.
Scenario 2: the second RDP session (through mstsc.exe) should be able to use the redirected smart card normally.

I have limited access to the macOS device to test the client, but I'm able to obtain additional logs (FreeRDP or OS), if necessary.

Thanks!

**Comment by akallabeth** [comment]
@vscfreire thanks for the feedback.
MacOS has its own implementation of the `PCSC API` with its own quirks.
Could you add the logs for the disconnect? Maybe it is as simple as some return value conversion.

**Comment by vscfreire** [comment]
With the latest changes, it no longer drops the connection when running the `scard-tester` tool, but the tool crashes in the middle of the tests.

I'm attaching the resulting logs from running the client with `DEBUG` enabled for the `com.freerdp.channels.smartcard.client` logging facility, but I can't see much there. Is there any additional logging or debugging which could be useful?

```
[18:52:02:317] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardIntroduceReaderGroupA failed with error SCARD_E_UNSUPPORTED_FEATURE [-2146435038]
[18:52:02:317] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardIntroduceReaderGroupA (0x00090050), status: SCARD_E_UNSUPPORTED_FEATURE (0x80100022)
[18:52:02:368] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardIntroduceReaderGroupW failed with error SCARD_E_UNSUPPORTED_FEATURE [-2146435038]
[18:52:02:368] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardIntroduceReaderGroupW (0x00090054), status: SCARD_E_UNSUPPORTED_FEATURE (0x80100022)
[18:52:02:438] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardIntroduceReaderA failed with error SCARD_E_UNSUPPORTED_FEATURE [-2146435038]
[18:52:02:438] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardIntroduceReaderA (0x00090060), status: SCARD_E_UNSUPPORTED_FEATURE (0x80100022)
[18:52:02:471] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardIntroduceReaderW failed with error SCARD_E_UNSUPPORTED_FEATURE [-2146435038]
[18:52:02:471] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardIntroduceReaderW (0x00090064), status: SCARD_E_UNSUPPORTED_FEATURE (0x80100022)
[18:52:03:259] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardLocateCardsW failed with error SCARD_E_UNSUPPORTED_FEATURE [-2146435038]
[18:52:03:259] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardLocateCardsByATRB (0x000900EC), status: SCARD_E_UNSUPPORTED_FEATURE (0x80100022)
[18:52:03:466] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetReaderIconW failed with error SCARD_E_UNSUPPORTED_FEATURE [-2146435038]
[18:52:03:466] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetReaderIcon (0x00090104), status: SCARD_E_UNSUPPORTED_FEATURE (0x80100022)
[18:52:03:496] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetReaderIconW failed with error SCARD_E_UNSUPPORTED_FEATURE [-2146435038]
[18:52:03:496] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetReaderIcon (0x00090104), status: SCARD_E_UNSUPPORTED_FEATURE (0x80100022)
[18:52:22:619] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardControl failed with error SCARD_E_NOT_TRANSACTED [-2146435050]
[18:52:22:619] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardControl (0x000900D4), status: SCARD_E_NOT_TRANSACTED (0x80100016)
[18:52:30:041] [52995:0eba9000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetReaderIconW failed with error SCARD_E_UNSUPPORTED_FEATURE [-2146435038]
[18:52:30:041] [52995:0eba9000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetReaderIcon (0x00090104), status: SCARD_E_UNSUPPORTED_FEATURE (0x80100022)
[18:52:43:437] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:43:437] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:43:458] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:43:458] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:43:915] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:43:915] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:44:032] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:44:032] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:44:104] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:44:105] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:44:129] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:44:129] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:44:150] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:44:151] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:44:186] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:44:186] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:44:216] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:44:216] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:44:249] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:44:250] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:44:408] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:44:408] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:44:457] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:44:458] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:44:541] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:44:541] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:44:559] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:44:559] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:44:588] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:44:588] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:44:647] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:44:647] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:44:771] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:44:771] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:55:890] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:55:890] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:55:927] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:55:927] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:55:953] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:55:953] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:56:010] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:56:010] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:56:045] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:56:045] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:56:076] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:56:077] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:52:56:118] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INSUFFICIENT_BUFFER [-2146435064]
[18:52:56:118] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INSUFFICIENT_BUFFER (0x80100008)
[18:53:10:922] [52995:0f356000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_UNSUPPORTED_FEATURE [-2146435038]
[18:53:10:922] [52995:0f356000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_UNSUPPORTED_FEATURE (0x80100022)
[18:53:39:710] [52995:1128d000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetStatusChangeW failed with error SCARD_E_CANCELLED [-2146435070]
[18:53:39:710] [52995:1128d000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetStatusChangeW (0x000900A4), status: SCARD_E_CANCELLED (0x80100002)
[18:53:39:711] [52995:11310000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetStatusChangeW failed with error SCARD_E_CANCELLED [-2146435070]
[18:53:39:711] [52995:11310000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetStatusChangeW (0x000900A4), status: SCARD_E_CANCELLED (0x80100002)
[18:53:39:711] [52995:10f7b000] [ERROR][com.freerdp.channels.rdpdr.client] - pVirtualChannelWriteEx failed with CHANNEL_RC_BAD_CHANNEL_HANDLE [00000007]
[18:53:39:711] [52995:10f7b000] [ERROR][com.freerdp.channels.rdpdr.client] - pVirtualChannelWriteEx failed with CHANNEL_RC_BAD_CHANNEL_HANDLE [00000007]
```

**Comment by akallabeth** [comment]
@vscfreire define `crash`, either you ommitted that from the log or there was a disconnect?
As for the reset,  this looks like it is missing all debug log messages?
1. How did you create the log (command line, ...)
2. Compile flags

**Comment by vscfreire** [comment]
So sorry for not explaining corretly.

When I say crash, I'm referring to the `scard-tester` tool crashing before ending all tests. The RDP connection through FreeRDP now remains OK.

In fact I was not enabling `DEBUG` logs correct, and was able to do so now... However, with `DEBUG` logs enabled, the client which uses FreeRDP is crashing with a Segmentation fault (and this happens on Windows, Linux and macOS). These are the last lines of debug:

```
[14:20:27:120] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - SCardEstablishContext (0x00090014) FileId: 1 CompletionId: 1
[14:20:27:120] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - EstablishContext_Call {
[14:20:27:120] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - dwScope: SCARD_SCOPE_USER (0x00000000)
[14:20:27:120] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:27:121] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - EstablishContext_Return {
[14:20:27:121] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] -   ReturnCode: SCARD_S_SUCCESS (0x00000000)
[14:20:27:121] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - hContext: { 609BD90D00000000 }
[14:20:27:121] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:27:129] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - SCardListReadersA (0x00090028) FileId: 1 CompletionId: 1
[14:20:27:129] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - ListReadersA_Call {
[14:20:27:129] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - hContext: { 609BD90D00000000 }
[14:20:27:129] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - cBytes: 0 mszGroups: (nil) fmszReadersIsNULL: 0 cchReaders: 0x00000400
[14:20:27:129] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:27:129] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - ListReadersA_Return {
[14:20:27:129] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   ReturnCode: SCARD_S_SUCCESS (0x00000000)
[14:20:27:129] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   cBytes: 41 msz: Gemalto PC Twin Reader (6BEB1702) 00 00,
[14:20:27:129] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:27:138] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - SCardListReadersA (0x00090028) FileId: 1 CompletionId: 1
[14:20:27:138] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - ListReadersA_Call {
[14:20:27:138] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - hContext: { 609BD90D00000000 }
[14:20:27:138] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - cBytes: 0 mszGroups: (nil) fmszReadersIsNULL: 0 cchReaders: 0x00000400
[14:20:27:138] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:27:138] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - ListReadersA_Return {
[14:20:27:138] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   ReturnCode: SCARD_S_SUCCESS (0x00000000)
[14:20:27:138] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   cBytes: 41 msz: Gemalto PC Twin Reader (6BEB1702) 00 00,
[14:20:27:138] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:27:146] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - SCardListReadersA (0x00090028) FileId: 1 CompletionId: 1
[14:20:27:146] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - ListReadersA_Call {
[14:20:27:146] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - hContext: { 609BD90D00000000 }
[14:20:27:146] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - cBytes: 0 mszGroups: (nil) fmszReadersIsNULL: 0 cchReaders: 0x00000400
[14:20:27:147] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:27:147] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - ListReadersA_Return {
[14:20:27:147] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   ReturnCode: SCARD_S_SUCCESS (0x00000000)
[14:20:27:147] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   cBytes: 41 msz: Gemalto PC Twin Reader (6BEB1702) 00 00,
[14:20:27:147] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:29:337] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - SCardListReadersA (0x00090028) FileId: 1 CompletionId: 1
[14:20:29:337] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - ListReadersA_Call {
[14:20:29:337] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - hContext: { 609BD90D00000000 }
[14:20:29:337] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - cBytes: 0 mszGroups: (nil) fmszReadersIsNULL: 0 cchReaders: 0x00000400
[14:20:29:337] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:29:337] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - ListReadersA_Return {
[14:20:29:337] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   ReturnCode: SCARD_S_SUCCESS (0x00000000)
[14:20:29:337] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   cBytes: 41 msz: Gemalto PC Twin Reader (6BEB1702) 00 00,
[14:20:29:337] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:29:345] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - SCardGetStatusChangeA (0x000900A0) FileId: 1 CompletionId: 1
[14:20:29:345] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - GetStatusChangeA_Call {
[14:20:29:345] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - hContext: { 609BD90D00000000 }
[14:20:29:345] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - dwTimeOut: 0x0000000A cReaders: 1
[14:20:29:345] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - 	[0]: szReader: Gemalto PC Twin Reader (6BEB1702) 00 00 cbAtr: 0
[14:20:29:346] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - 	[0]: dwCurrentState: SCARD_STATE_UNAWARE (0x00000000)
[14:20:29:346] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - 	[0]: dwEventState: SCARD_STATE_IGNORE | SCARD_STATE_UNKNOWN | SCARD_STATE_EMPTY | SCARD_STATE_ATRMATCH | SCARD_STATE_MUTE (0x00000255)
[14:20:29:346] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:29:346] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - GetStatusChangeA_Return {
[14:20:29:346] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   ReturnCode: SCARD_S_SUCCESS (0x00000000)
[14:20:29:346] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   cReaders: 1
[14:20:29:346] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -     [0]: dwCurrentState: SCARD_STATE_UNAWARE (0x00000000)
[14:20:29:346] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -     [0]: dwEventState: SCARD_STATE_CHANGED | SCARD_STATE_PRESENT (0x00010022)
[14:20:29:346] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -     [0]: cbAtr: 25 rgbAtr: { 3BFF9600008131FE4380318065B085040120120FFF829000D0 }
[14:20:29:346] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:29:353] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - SCardGetStatusChangeA (0x000900A0) FileId: 1 CompletionId: 1
[14:20:29:353] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - GetStatusChangeA_Call {
[14:20:29:353] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - hContext: { 609BD90D00000000 }
[14:20:29:353] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - dwTimeOut: 0x00000000 cReaders: 1
[14:20:29:353] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - 	[0]: szReader: Gemalto PC Twin Reader (6BEB1702) 00 00 cbAtr: 25
[14:20:29:353] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - 	[0]: dwCurrentState: SCARD_STATE_PRESENT (0x00010020)
[14:20:29:353] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - 	[0]: dwEventState: SCARD_STATE_CHANGED | SCARD_STATE_PRESENT (0x00010022)
[14:20:29:353] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:29:356] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - SCardGetStatusChangeA failed with error SCARD_E_TIMEOUT [-2146435062]
[14:20:29:356] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - GetStatusChangeA_Return {
[14:20:29:356] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   ReturnCode: SCARD_E_TIMEOUT (0x8010000A)
[14:20:29:356] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   cReaders: 1
[14:20:29:356] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -     [0]: dwCurrentState: SCARD_STATE_PRESENT (0x00010020)
[14:20:29:356] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -     [0]: dwEventState: SCARD_STATE_PRESENT (0x00010020)
[14:20:29:356] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -     [0]: cbAtr: 25 rgbAtr: { 3BFF9600008131FE4380318065B085040120120FFF829000D0 }
[14:20:29:356] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:29:364] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - SCardListReadersA (0x00090028) FileId: 1 CompletionId: 1
[14:20:29:364] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - ListReadersA_Call {
[14:20:29:364] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - hContext: { 609BD90D00000000 }
[14:20:29:364] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - cBytes: 0 mszGroups: (nil) fmszReadersIsNULL: 0 cchReaders: 0x00000400
[14:20:29:364] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:29:364] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - ListReadersA_Return {
[14:20:29:364] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   ReturnCode: SCARD_S_SUCCESS (0x00000000)
[14:20:29:364] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   cBytes: 41 msz: Gemalto PC Twin Reader (6BEB1702) 00 00,
[14:20:29:364] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:29:373] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - SCardGetStatusChangeA (0x000900A0) FileId: 1 CompletionId: 1
[14:20:29:373] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - GetStatusChangeA_Call {
[14:20:29:373] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - hContext: { 609BD90D00000000 }
[14:20:29:373] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - dwTimeOut: 0x00000000 cReaders: 1
[14:20:29:373] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - 	[0]: szReader: Gemalto PC Twin Reader (6BEB1702) 00 00 cbAtr: 0
[14:20:29:373] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - 	[0]: dwCurrentState: SCARD_STATE_UNAWARE (0x00000000)
[14:20:29:373] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - 	[0]: dwEventState: SCARD_STATE_IGNORE | SCARD_STATE_UNKNOWN | SCARD_STATE_EMPTY | SCARD_STATE_ATRMATCH | SCARD_STATE_MUTE (0x00000255)
[14:20:29:373] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:29:374] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - GetStatusChangeA_Return {
[14:20:29:374] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   ReturnCode: SCARD_S_SUCCESS (0x00000000)
[14:20:29:374] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   cReaders: 1
[14:20:29:374] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -     [0]: dwCurrentState: SCARD_STATE_UNAWARE (0x00000000)
[14:20:29:374] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -     [0]: dwEventState: SCARD_STATE_CHANGED | SCARD_STATE_PRESENT (0x00010022)
[14:20:29:374] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -     [0]: cbAtr: 25 rgbAtr: { 3BFF9600008131FE4380318065B085040120120FFF829000D0 }
[14:20:29:374] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:29:382] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - SCardConnectA (0x000900AC) FileId: 1 CompletionId: 1
[14:20:29:382] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - ConnectA_Call {
[14:20:29:382] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - hContext: { 609BD90D00000000 }
[14:20:29:382] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - szReader: Gemalto PC Twin Reader (6BEB1702) 00 00 dwShareMode: SCARD_SHARE_SHARED (0x00000002) dwPreferredProtocols: SCARD_PROTOCOL_Tx (0x00000003)
[14:20:29:382] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:29:465] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - Connect_Return {
[14:20:29:465] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   ReturnCode: SCARD_S_SUCCESS (0x00000000)
[14:20:29:465] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - hContext: { 609BD90D00000000 }
[14:20:29:465] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   hContext: { 9633496A00000000 }
[14:20:29:465] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] -   dwActiveProtocol: SCARD_PROTOCOL_T1 (0x00000002)
[14:20:29:465] [61512:61626] [DEBUG][com.freerdp.channels.smartcard.client] - }
[14:20:29:690] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - SCardStatusA (0x000900C8) FileId: 1 CompletionId: 1
[14:20:29:690] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - StatusA_Call {
[14:20:29:690] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - hContext: { 609BD90D00000000 }
[14:20:29:690] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] -   hContext: { 9633496A00000000 }
[14:20:29:690] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - fmszReaderNamesIsNULL: 1 cchReaderLen: 0 cbAtrLen: 64
[14:20:29:690] [61512:61598] [DEBUG][com.freerdp.channels.smartcard.client] - }
Signal: SIGSEGV (Segmentation fault)
```

The segmentation fault appears to happen on a smartcard related function (where logging is performed):

```
__memmove_sse2_unaligned_erms 0x00007f56d6eaae10
smartcard_convert_string_list 0x00005608640f9848
smartcard_trace_status_return.isra 0x00005608640fb97f
smartcard_pack_status_return 0x0000560864106dcb
smartcard_irp_device_control_call 0x00005608640f81a9
smartcard_context_thread 0x00005608640f2e8f
thread_launcher 0x000056086424ca4c
start_thread 0x00007f56df971609
clone 0x00007f56d6f0e293
```

This segmentation fault example is the client running on Linux.

**Comment by akallabeth** [comment]
ok, this crash is strange, which compile options did you use? this looks like some overaggressive optimization result

**Comment by vscfreire** [comment]
Hello, and sorry for the late response.

I'm compiling FreeRDP with the standard CMake CFLAGS, and options described below.

On Windows (using VS2019), I added the `/Od` to disable optimizations, and the problem still occurs:
```
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_EXECINFO_H= HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_SYSLOG_H= HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H= HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TM_GMTOFF= HAVE_UNISTD_H= WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_MEDIA_FOUNDATION=OFF WITH_NATIVE_SSPI=ON WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_PROFILER=OFF WITH_SAMPLE=OFF WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_WIN8=OFF WITH_WINMM=ON WITH_WINPR_TOOLS=ON WITH_X264=OFF
Build type:          Release
CFLAGS:              /DWIN32 /D_WINDOWS  /Gd /W3 /Od
Compiler:            MSVC, 19.28.29337.0
Target architecture: x64
```

Segmentation fault stack trace (Windows):
```
memmove 0x00007ffe13aa1530
smartcard_irp_device_control_decode 0x00007ff7bbd2a702
smartcard_trace_reconnect_call 0x00007ff7bbd344fc
smartcard_pack_status_return 0x00007ff7bbd2e566
smartcard_irp_device_control_call 0x00007ff7bbd27b15
smartcard_context_new 0x00007ff7bbd2380b
BaseThreadInitThunk 0x00007ffe37277034
RtlUserThreadStart 0x00007ffe3879d241
```

On Linux (using gcc), also using "-O0" to disable optimizations:
```
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=OFF WITH_X264=OFF WITH_XINERAMA=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -O0
Compiler:            GNU, 9.3.0
Target architecture: x64
```

Segmentation fault stack trace (Linux):
```
__memmove_sse2_unaligned_erms 0x00007f565cd37e10
smartcard_convert_string_list 0x000055e819789118
smartcard_trace_status_return.isra 0x000055e81978b24f
smartcard_pack_status_return 0x000055e81979669b
smartcard_irp_device_control_call 0x000055e819787a79
smartcard_context_thread 0x000055e81978275f
thread_launcher 0x000055e8198dc31c
start_thread 0x00007f5665853609
clone 0x00007f565cd9b293
```

Notice that this doesn't happen with any smart card log message, a lot of them are printed before the segmentation fault. Apparently, only when I try to *use*  the smartcard (by opening an application which uses the card) does the segmentation fault occur.

**Comment by vscfreire** [comment]
Also, compiled the Windows client from the `master` branch, with no changes, and tested this using `wfreerdp.exe`.

When running normally, it works. When using `/log-level:DEBUG`, crashes the client when trying to use the smartcard on an application.

**Comment by vscfreire** [comment]
@akallabeth This issue was closed but the SC MacOS support still has issues and there's the crash with logging in several platforms. Should I create a different issue for the logging problem? Please tell me if there is anything I can do to help.

**Comment by akallabeth** [comment]
@vscfreire there are other crashers? did run it on my mac test machine for quite some time after the referenced fix, or are you referring to other issues with pcsc?

**Comment by vscfreire** [comment]
@akallabeth Hello.

Well, there are two issues, one is related to the macOS client specifically, which is that the `scard-tester` tool crashes before completing all tests when connecting with the macOS client:

![macos-client-scard-crash](https://user-images.githubusercontent.com/35369554/109556034-3373a280-7ace-11eb-93ba-3867b9b5e966.png)

When using the Windows or Linux clients, the tests run until the end and the `scard-tester` program exits normally.

The second issue is not macOS specific, but the logging problem which was reported in the previous comments. When using the `/log-level:DEBUG` flag on any client (Linux, macOS, Windows), on the first smartcard access attempt (using any smartcard enabled app or the `scard-tester` tool) the client itself crashes immediately with a segmentation fault.

All these tests were performed with the latest commit on the `stable-2.0` branch.

**Comment by akallabeth** [comment]
@vscfreire ok, you have a real lucky hand. Did find a broken format string, but that did not crash the program on my machines for some reason. Anyway, that part is fixed now.

**Comment by akallabeth** [comment]
@vscfreire did you have time to test the fix?

**Comment by vscfreire** [comment]
@akallabeth Hi, sorry for not replying earlier.

Tested the latest stable-2.0 branch (including commit #6854, also related to smartcards) and unfortunately both issues are still happening, although the /log-level:DEBUG one seems slightly better.

1. Regarding the scard-tester tool crashing on MacOS: here's the output of the MacFreeRDP application itself when the tool crashes, not sure if it's relevant but I can include the full log if needed:

```
[22:06:39:106] [39927:00627000] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_UNSUPPORTED_FEATURE [-2146435038]
[22:06:39:106] [39927:00627000] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_UNSUPPORTED_FEATURE (0x80100022)
```


2. Regarding the /log-level:DEBUG crash: at least on MacOS, FreeRDP no longer crashes with scard-tester tool, but other programs that access the smartcard still cause FreeRDP to crash. Here's the output of FreeRDP immediately before the crash:

```
[21:38:26:684] [37186:04898000] [DEBUG][com.freerdp.channels.smartcard.client] - SCardStatusA (0x000900C8) FileId: 1 CompletionId: 4
[21:38:26:684] [37186:04898000] [DEBUG][com.freerdp.channels.smartcard.client] - StatusA_Call {
[21:38:26:684] [37186:04898000] [DEBUG][com.freerdp.channels.smartcard.client] - hContext: { 1400000000000000 }
[21:38:26:684] [37186:04898000] [DEBUG][com.freerdp.channels.smartcard.client] -   hContext: { 0800000000000000 }
[21:38:26:684] [37186:04898000] [DEBUG][com.freerdp.channels.smartcard.client] - fmszReaderNamesIsNULL: 1 cchReaderLen: 0 cbAtrLen: 64
[21:38:26:684] [37186:04898000] [DEBUG][com.freerdp.channels.smartcard.client] - }
[21:38:26:684] [37186:0499e000] [INFO][com.freerdp.utils] - Caught signal 'Segmentation fault: 11' [11]
```

And here's the stack trace from the Apple Problem Report:

```
0   libsystem_kernel.dylib        	0x00007fff203fd462 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff2042b610 pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff2030dba3 raise + 26
3   libfreerdp2.2.3.2.dylib       	0x000000010a47aad3 fatal_handler + 227
4   libsystem_platform.dylib      	0x00007fff2046fd7d _sigtramp + 29
5   ???                           	000000000000000000 0 + 0
6   libfreerdp-client2.2.3.2.dylib	0x000000010a41521b smartcard_convert_string_list + 171
7   libfreerdp-client2.2.3.2.dylib	0x000000010a409e63 smartcard_pack_status_return + 115
8   libfreerdp-client2.2.3.2.dylib	0x000000010a418bcb smartcard_irp_device_control_call + 9803
9   libfreerdp-client2.2.3.2.dylib	0x000000010a40083b smartcard_context_thread + 315
10  libwinpr2.2.3.2.dylib         	0x000000010a674e8c thread_launcher + 108
11  libsystem_pthread.dylib       	0x00007fff2042b950 _pthread_start + 224
12  libsystem_pthread.dylib       	0x00007fff2042747b thread_start + 15
```

Let me know if you'd like me to run further tests or provide more information.

**Comment by akallabeth** [comment]
@vscfreire this looks like the crash that I experienced that was fixed with 471cda7ef304afb27c2fd1aa5a59078c7401e46e
I´ve been running this with the most recent version of `scard-tester` (`1.0.2`) several times on my test mac and did not encounter any crash with that revision. (current `stable-2.0` branch)
Could it be that there was a mixup or the binaries were not up to date?

**Comment by akallabeth** [comment]
@vscfreire ok, now ran `scard_v1.0.2.exe` with and without a cardreader attached on 2 different macs with:
`<app> /v:<server> /network:auto /smartcard /log-level:trace` and I could not produce any crashes (even with `asan` builds) with `>100` runs (scripted)

**Comment by vscfreire** [comment]
@akallabeth I also considered there being a mixup, but unfortunately after a clean clone and compilation of the MacOS FreeRDP client, scard_v1.0.2.exe is still crashing when run. Maybe different smartcard types is the reason why it's crashing for me but not for you?

**Comment by vscfreire** [comment]
Regarding MacOS FreeRDP crashing with a segfault with the `/log-level:debug` flag, I believe I found a method to reproduce this consistently:

1. Install the [OpenSC Tools ](https://github.com/OpenSC/OpenSC/releases/download/0.21.0/OpenSC-0.21.0_win64.msi) on the remote windows server (only the command-line tools are needed).
2. Connect to the windows server with the MacFreeRDP client, with flags `/smartcard /log-level:debug`.
3. In the remote session, open CMD and run the following command: `"C:\Program Files\OpenSC Project\OpenSC\tools\pkcs15-tool.exe" -D`
4. MacFreeRDP crashes with a segfault.

Keep in mind I just tested the same method in the Windows client and it didn't crash, where previously these crashes were happening in both clients. Also I can no longer reproduce the client crash with other programs like scard_v1.0.2.exe or opensc-tool -r 0 -a. This leads me to believe that commit #6854 did fix most of the issues, but there's still a specific operation that causes the crash only on the MacOS client.

**Comment by akallabeth** [comment]
@vscfreire ok, I still fail to reproduce. can you run the thing in a debugger (best compiled with debug symbols or debug configuration)?
a full stack trace could be really helpful here.
Tested with a gemalto reader and a yubikey neo here, so I think it may be reader related.

**Comment by vscfreire** [comment]
@akallabeth it is in fact reader related! By coincidence I also have a Gemalto Reader, I tested it with the above method and MacFreeRDP never crashed.

Here's the stack trace from a MacFreeRDP crash using the faulting reader, using FreeRDP compiled with CMAKE_BUILD_TYPE=Debug:

```
* thread #48, stop reason = EXC_BAD_ACCESS (code=1, address=0x3)
  * frame #0: 0x00007fff2046d0cd libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell + 77
    frame #1: 0x000000010c060fd5 libfreerdp-client2.2.dylib`smartcard_convert_string_list(in=0x0000000000000000, bytes=20, unicode=NO) at smartcard_pack.c:371:3
    frame #2: 0x000000010c05600e libfreerdp-client2.2.dylib`smartcard_trace_status_return(smartcard=0x00007f8464db34a0, ret=0x000070000ccbfdb8, unicode=NO) at smartcard_pack.c:1293:20
    frame #3: 0x000000010c055e1b libfreerdp-client2.2.dylib`smartcard_pack_status_return(smartcard=0x00007f8464db34a0, s=0x00007f8464c95940, ret=0x000070000ccbfdb8, unicode=NO) at smartcard_pack.c:2745:2
    frame #4: 0x000000010c067403 libfreerdp-client2.2.dylib`smartcard_StatusA_Call(smartcard=0x00007f8464db34a0, operation=0x00007f8464c98380) at smartcard_operations.c:1622:11
    frame #5: 0x000000010c064949 libfreerdp-client2.2.dylib`smartcard_irp_device_control_call(smartcard=0x00007f8464db34a0, operation=0x00007f8464c98380) at smartcard_operations.c:2578:13
    frame #6: 0x000000010c04a227 libfreerdp-client2.2.dylib`smartcard_context_thread(arg=0x00007f8464de2480) at smartcard_main.c:111:19
```

scard_v1.0.2.exe still fails with the Gemalto Reader however.

**Comment by akallabeth** [comment]
@vscfreire ok, thank you for that. you should file a bug report with the reader vendor/driver :)
They return a `NULL` buffer but tell you it is `20 bytes` long...
(`SCardStatusA` is called with `pcchReaderLen=SCARD_AUTOALLOCATE` and `mszReaderNames=NULL` after the call)

**Comment by akallabeth** [comment]
@vscfreire as for `scard_v1.0.2.exe still fails with the Gemalto Reader however.` what do you mean? the tool just issues a lot of `SCard` API calls, not all of them must succeed.

**Comment by vscfreire** [comment]
@akallabeth noted =). I've tested with the latest commits, and can confirm that the faulty smartcard reader no longer crashes MacFreeRDP.

As for `scard_v1.0.2.exe still fails`, apologies, I should have been more clear. Even with Gemalto and the latest commits, scard_v1.0.2.exe still crashes with the "scard_v1.0.2.exe has stopped working" popup, on MacFreeRDP only. 

Version 1.0.2 includes a bit more information compared to my previous screenshot:

```
SCardGetAttrib nullptr failed with SCARD_E_UNSUPPORTED_FEATURE
SCardGetAttrib buffersize failed with SCARD_E_UNSUPPORTED_FEATURE
SCardGetAttrib SCARD_AUTOALLOCATE failed with SCARD_E_UNSUPPORTED_FEATURE
SCardGetAttrib [4294967295]
```

The MacFreeRDP logs don't seem to indicate nothing out of the ordinary. scard_v1.0.2.exe finishes normally on the Windows FreeRDP client, using the same Gemalto reader and smartcard.

**Comment by akallabeth** [comment]
@vscfreire ok, then closing this as resolved.
Note: the `scard` utility crash is a missing return check (we now pass on the buggy return data from the driver without modification)

**Comment by vscfreire** [comment]
@akallabeth Thanks for your effort! In reality I reported this issue because I have to use my company jump server to sign documents in another server with my national ID card. So, basically, I connect from my Mac to a Windows Server 2016 jump server and then, using the Microsoft RDP Client to a final signing server Windows Server 2016.

If I use my Windows laptop, this scenario works perfectly with FreeRDP. If I use my Mac, the jump server RDP client freezes when I try to use the signing application in the final signing server. If instead of FreeRDP, I use the Mac Microsoft RDP Client, to connect to the jump server, the signing in the final server doesn't freeze the connection.

Should I open a specific issue with this use case?

**Comment by akallabeth** [comment]
@vscfreire yes, that would be helpful. It looks like we need to dig deeper into the specifics of the mac implementation of pcsc :/
