### ISSUE TITLE
freerdp-shadow-cli: issues with GFX channel and MSTSC

### ISSUE THREAD

**Issue by efferre79** [FreeRDP/FreeRDP#9660]
**Describe the bug**
I am using freerdp-shadow-cli to implement a RDP shadow server under Linux (I am using X11). I am trying to connect from a Windows 10 machine by using the stock RDP client (mstsc.exe 10.0.19041.3636). Both computers are in the same LAN..

I am using the following command line to start the server as a regular user

`$ freerdp-shadow-cli /sec:nla /sam-file:/etc/freerdp/SAM /port:9833  /log-level:TRACE

Sometimes I am able to connect from the client but I noticed the reported error indicated in the title of this issue. Other times instead the client cannot connect because the process is closed during evaluation of connection quality, in that case the error is the following:

`Because of a protocol error, this session will be disconnected. Please try connecting to the remote computer again.`

I don't know if this client error is related to the server error because the _invalid TPKT header error_ always appears in the server log even when the connection is successful.

I have also tried running remmina, based on freerdp2, from a Linux virtual machine (Ubuntu 22.04.3 LTS) installed on the same Windows machine used for the tests. In this case I don't see the same error in the server so I guess there is some incompatibility with the Microsoft client. Moreover the connection is reliably established and I don't get problems as reported above with the Windows client.

**To Reproduce**

1. start the server as indicated above on the Linux machine
2. use the windows RDP client to connect to the server (accept the invalid certificate)

**Expected behavior**
I expect to connect to the server without problems with the Windows client (every time I try).

**Screenshots**
non applicable

**Application details**
* FreeRDP version 3.0.0
* freerdp-shadow-cli /buildconfig
[12:33:04:919] [24727:00006097] [INFO][com.freerdp.server.shadow] - [shadow_server_command_line_status_print]: Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=OFF WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=OFF WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL_AVAILABLE=1 WITH_CUPS=ON WITH_DEBUG_ALL=ON WITH_DEBUG_CAPABILITIES=ON WITH_DEBUG_CERTIFICATE=ON WITH_DEBUG_CHANNELS=ON WITH_DEBUG_CLIPRDR=ON WITH_DEBUG_CODECS=ON WITH_DEBUG_DVC=ON WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=ON WITH_DEBUG_LICENSE=ON WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=ON WITH_DEBUG_NLA=ON WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=ON WITH_DEBUG_RDP=ON WITH_DEBUG_RDPDR=ON WITH_DEBUG_RDPEI=ON WITH_DEBUG_RDPGFX=ON WITH_DEBUG_REDIR=ON WITH_DEBUG_RFX=ON WITH_DEBUG_RINGBUFFER=ON WITH_DEBUG_SCARD=ON WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=ON WITH_DEBUG_SVC=ON WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=ON WITH_DEBUG_TRANSPORT=ON WITH_DEBUG_TSG=ON WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=ON WITH_DEBUG_X11=ON WITH_DEBUG_X11_LOCAL_MOVESIZE=ON WITH_DEBUG_XV=ON WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FUSE=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSTREAMER_1_0=ON WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_NEON=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_OPUS=OFF WITH_OSS=OFF WITH_PCSC=OFF WITH_PKCS11=OFF WITH_PLATFORM_SERVER=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_PULSE=ON WITH_RDTK=ON WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_SYSTEMD=OFF WITH_THIRD_PARTY=OFF WITH_UNICODE_BUILTIN=OFF WITH_URIPARSER=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=ON WITH_WEBVIEW=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XV=ON
Build type:          RelWithDebInfo
CFLAGS:              -march=core2 -O2 -pipe -Wall -Wpedantic -Wno-padded -Wno-cast-align -Wno-declaration-after-statement -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer
Compiler:            GNU, 12.3.1
Target architecture: x64
* OS version server side: Gentoo Linux
* OS version client side: Windows 10 Pro 22H2 19045.3693
* [Here](https://gist.github.com/efferre79/99770374465b9be7cfde3fd702a9a4fc) are the two log outputs when the connection is or is not successfully established between the Windows RDP client and the Freerdp shadow server.

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Gentoo
 - Architecture: amd64

**Additional context**
nothing

**Comment by efferre79** [comment]
I have just tested with freerdp-2.11.1 and it works as expected so the problems here described are not present. It's definitely a regression!

**Comment by akallabeth** [comment]
@efferre79
1. the `Received invalid TPKT header length` message is due to a protocol violation (or just wrongly documented?) in info packet, not related to your issues.
1. so you build shadow from `2.11.1` and it works with `mstsc` or you connect with  `xfreerdp`?
2. from your logs I can see that sometimes authentication fails at negotiation stage, but need to check what is going on.

**Comment by efferre79** [comment]
>     1. the `Received invalid TPKT header length` message is due to a protocol violation (or just wrongly documented?) in info packet, not related to your issues.

Yes, that seems the case. For version 2.11.1 I noticed that kind of error is not present
 
>     2. so you build shadow from `2.11.1` and it works with `mstsc` or you connect with  `xfreerdp`?

Yes, I confirm I tested shadow server 2.11.1 against mstsc too. In that case I don't see the `Received invalid TPKT header length` error messages and the connection tries are reliable (N tries => N successful connections)

>     3. from your logs I can see that sometimes authentication fails at negotiation stage, but need to check what is going on.

If you mean the errors after `BIO_read returned a system error 104`, those are also available with version 2.11.1 and not only with the latest 3.0.0

**Comment by akallabeth** [comment]
ok, I can not reproduce this. only thing I found is a bug in error handling when X11 is not available fixed with https://github.com/FreeRDP/FreeRDP/pull/9661

what did I do:
1. create `SAM` file with `winpr-hash  -u user -d domain -p pwd -v1 -f sam >SAM`
1. run `Xephyr :23 -screen 1280x768`
2. run `DISPLAY=:23 xterm&`
3. run `DISPLAY-:23 openbox&`
4. run `DISPLAY=:23 /tmp/xxx/bin/freerdp-shadow-cli /sec:nla /sam-file:SAM /port:3333`
5. connect with `mstsc`  from (win 10 22H2)
1. repeat (15x)

I never had a failed connection, even tried to do some invalid auth in between.

<details><summary>freerdp-shadow-cli /buildconfig</summary>
```
freerdp-shadow-cli /buildconfig
[19:24:06:446] [820885:000c8695] [INFO][com.freerdp.server.shadow] - [shadow_server_command_line_status_print]: Build configuration: BUILD_TESTING=ON WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=ON WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL_AVAILABLE=1 WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FUSE=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_KRB5=ON WITH_KRB5_NO_NTLM_FALLBACK=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_OPAQUE_SETTINGS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSC_PKCS11_LINKED=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OPUS=OFF WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PKCS11=ON WITH_PLATFORM_SERVER=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_PULSE=OFF WITH_RDTK=ON WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_SYSTEMD=ON WITH_THIRD_PARTY=OFF WITH_UNICODE_BUILTIN=OFF WITH_URIPARSER=ON WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WEBVIEW=OFF WITH_WEBVIEW_QT=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Debug
CFLAGS:               -Wall -Wpedantic -Wno-padded -Wno-cast-align -Wno-declaration-after-statement -fPIC -Wall -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -fsanitize=address -fsanitize-address-use-after-scope
Compiler:            GNU, 13.2.1
Target architecture: x64
```
</details>

**Comment by akallabeth** [comment]
@efferre79 maybe try a build without all the debug options (they slow down the whole thing a lot and are disabled for that reason), maybe that is killing the connection?
I can not find anything unusual in the logs other than that

**Comment by efferre79** [comment]
I don't think it's really an authentication issue (even if there is an error in the log), in fact with version 2.11.1 the connection is reliably done but I can still see the authentication errors in the log.

I am using mstsc with the default options. If I pass the wrong password on purpose then the connection is closed with an authentication error. If the credentials are correct, what happens is that I got authenticated but the connection is closed later when mstsc tries to optimize the connection (`estimating connection quality` message with wait bar).

The problem is visible only with freerdp 3.0.0 and not 2.11.1 so something is changed in the code for sure.

I have added to my xorg-server Xephyr support and tried as indicated in your test. In this case with freerdp 3.0.0 I don't see the same connection problems, [here](https://gist.github.com/efferre79/fcf06ce1faf8b6919a7b251fe8c0b9c0) is the log (also in this log there is the TKIP error message and the authentication errors noise but I inserted the credentials correctly at first try)

I don't know what is the difference between my x11 server (version 21.1.9) and the Xephyr one, the major difference is that the first one is using three real monitors. I have a screen size of 3840 x 1024 and I passed that value to Xephyr session and that works. What I noticed is that I can see the whole screen size for Xephyr while with x11 I can see only one monitor. Even if I use the option `/monitors:0,1,2` with freerdp-shadow-cli I still see only one.

BTW: Is there a way to log mstsc activity?

**Comment by pnowack** [comment]
> from your logs I can see that sometimes authentication fails at negotiation stage, but need to check what is going on.

mstsc has the habit to connect twice. First the authentication fails, then it connects again (I also know this behaviour from g-r-d). It might be the case, that mstsc sends the users actual local credentials first, don't know. Anyway not that important here.

@efferre79 What is the value of the preferred colour depth in mstsc? When you set it to '32-bit', will mstsc still show the protocol error message?

**Comment by efferre79** [comment]
> @efferre79 What is the value of the preferred colour depth in mstsc? When you set it to '32-bit', will mstsc still show the protocol error message?

I am using the default `Highest quality 32 bit` mode. I have just tested the other options 24, 16, 15 bit modes with the same result. I have also tried removing all the checkmarks in the Experience -> Performance tab of mstsc options but nothing changes in the result.

In my opinion it is very strange that with the default mstsc options, it works as expected with freerdp 2.11.1 while doesn't with latest 3.0.0.

**Comment by efferre79** [comment]
This is the error I get most of the times:
![error](https://github.com/FreeRDP/FreeRDP/assets/4586973/60dd6958-0553-4563-979f-2ea759653bca)

**Comment by akallabeth** [comment]
@efferre79 did you try a build without the overwhelming debug logs?
we´ve added quite a lot of normal logging to the library and the debug logs are deactivated by default for a reason.
it is also strange that I can not see anything suspicious in the logs, so could you create a clean log of a failing connection and upload that here?

**Comment by akallabeth** [comment]
@efferre79 I´ve fixed an issue with https://github.com/FreeRDP/FreeRDP/pull/9665 that might be the reason for your issues. can you give that branch a try?

**Comment by efferre79** [comment]
> @efferre79 did you try a build without the overwhelming debug logs? we´ve added quite a lot of normal logging to the library and the debug logs are deactivated by default for a reason. it is also strange that I can not see anything suspicious in the logs, so could you create a clean log of a failing connection and upload that here?

I added the debug info after facing the problem :-) Anyway, [here](https://gist.github.com/efferre79/700ba1498456513d692987b17bd9a233) is the version 3.0.0 log when compiled without debugging, same problem

**Comment by efferre79** [comment]
> @efferre79 I´ve fixed an issue with #9665 that might be the reason for your issues. can you give that branch a try?

I have tried that branch compiling without debug info

```
[12:02:43:239] [10210:000027e2] [INFO][com.freerdp.server.shadow] - [shadow_server_command_line_status_print]: FreeRDP version 3.0.1-dev0 (git f09cd41f5)

[12:02:19:587] [10177:000027c1] [INFO][com.freerdp.server.shadow] - [shadow_server_command_line_status_print]: Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=OFF WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=OFF WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL_AVAILABLE=1 WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FUSE=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSTREAMER_1_0=ON WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_NEON=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_OPUS=OFF WITH_OSS=OFF WITH_PCSC=OFF WITH_PKCS11=OFF WITH_PLATFORM_SERVER=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_PULSE=ON WITH_RDTK=ON WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_SYSTEMD=OFF WITH_THIRD_PARTY=OFF WITH_UNICODE_BUILTIN=OFF WITH_URIPARSER=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=ON WITH_WEBVIEW=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XV=ON
Build type:          Release
CFLAGS:              -march=core2 -O2 -pipe -Wall -Wpedantic -Wno-padded -Wno-cast-align -Wno-declaration-after-statement -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer
Compiler:            GNU, 12.3.1
Target architecture: x64
```

The problem is still present :-(

**Comment by efferre79** [comment]
Tested with latest commit from master FreeRDP version 3.0.1-dev0 (git 6c2698058), unfortunately this issue is not solved :-( Please reopen it.

I have tried further debugging the problem by bisecting git code. Unfortunately many commits don't compile or the compiled binary crashes or has issues so it's hard to find the problem without having a deep knowledge of the software code. Up to now I have been able to define the following commits:

```
good: 4d885e3a6efd0c45cb5760cb486961b35f21c080
bad: 39210d1efdb639d23efccd28523c16e45e2b6de9
```

There are only 736 commits. With the _good_ commit it is possible to get a connection to the shadow server but there is no image of the remote desktop (I think it's fine because not implemented at the time of that commit). With the _bad_ commit I can replicate the issue described here (protocol error). With the inner commits it's possible to face other problems (e.g. SAM lookup with empty domain, various asserts in winpr/libwinpr/sspi/sspi_winpr.c, etc) which are not related to the issue.

With the first _commit_ after good I get the following error:

```
[12:05:32:237] [4470:4506] [ERROR][com.freerdp.core.peer] - peer_recv_callback_internal: CONNECTION_STATE_CAPABILITIES_EXCHANGE - peer_recv_pdu() fail
[12:05:32:237] [4470:4506] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[12:05:32:237] [4470:4506] [ERROR][com.freerdp.client.shadow] - Failed to check FreeRDP file descriptor
```

so maybe someone can tell me which other commit fixes this. With the last commit before _bad_ I get
```[12:10:19:884] [10996:11003] [ERROR][com.winpr.sspi.NTLM] - Error: Could not find user in SAM database```
which is of course solved by the _bad_ commit itself.

To simplify the testing with the Windows RDP client I have written a command script [test_rdp.bat](https://gist.github.com/efferre79/c8bdc106cea7312a3dda1c7d24c75b61). It must be configured with the remote host info and with the number of tries to do. The software cannot distinguish the kind of errors from mstsc.exe so its behavior must be supervised, eventually it makes life easier with repetitive tries.

**Comment by efferre79** [comment]
@akallabeth please reopen this issue

I have finally tracked down to the first bad commit. I tested the inner commits described above by adding the  39210d1efdb639d23efccd28523c16e45e2b6de9 commit to avoid connection failures due to SAM lookup error with empty domain. Said that I get:

```
$ git bisect start
status: waiting for both good and bad commits
$ git bisect good 34f44ce4a184a2edaa586545cb20b152c859c891
status: waiting for bad commit, 1 good commit known
$ git bisect bad d6ab9d5f63df87bb2bf1195ec85d3d8b5095f887
d6ab9d5f63df87bb2bf1195ec85d3d8b5095f887 is the first bad commit
commit d6ab9d5f63df87bb2bf1195ec85d3d8b5095f887
Author: Armin Novak <anovak@thincast.com>
Date:   Sun Dec 18 17:23:14 2022 +0100

    [server,shadow] abort connection if a resize fails
    
    The shadow server tries to resize the client to use a compatible
    resolution. If that fails, e.g. if there is another resize request after
    the disconnect/reconnect sequence, abort the connection.

 include/freerdp/server/shadow.h |  4 ++
 server/shadow/shadow_client.c   | 83 +++++++++++++++++++++++++++++++----------
 2 files changed, 68 insertions(+), 19 deletions(-)

```

With the good commit the connection is successfully established but I cannot see any image of the remote server. With the bad commit I can see the image of the remote server but the connection is later aborted by the server itself. So at least we know the source of protocol error.

**Comment by pnowack** [comment]
> d6ab9d5f63df87bb2bf1195ec85d3d8b5095f887 is the first bad commit

[Looking through the changes of that commit](https://github.com/FreeRDP/FreeRDP/commit/d6ab9d5f63df87bb2bf1195ec85d3d8b5095f887), I would say the `shadow_send_desktop_resize()` call in the conditional path of `if (shadow_client_recalc_desktop_size(client))` should be changed to `if (shadow_send_desktop_resize(client)) return FALSE;`.
At least that part looks wrong, and I would have guessed that this would be (at least part of) the issue. It seems though on current master that was already changed.

One other thing, that looks sus to me is the `shadow_reset_desktop_resize()` procedure in that commit. The reactivation sequence is not instant, there are some PDUs that are reexchanged. So, I don't see, that this procedure has any meaningful impact.

**Comment by efferre79** [comment]
> [Looking through the changes of that commit](https://github.com/FreeRDP/FreeRDP/commit/d6ab9d5f63df87bb2bf1195ec85d3d8b5095f887), I would say the `shadow_send_desktop_resize()` call in the conditional path of `if (shadow_client_recalc_desktop_size(client))` should be changed to `if (shadow_send_desktop_resize(client)) return FALSE;`.
> At least that part looks wrong, and I would have guessed that this would be (at least part of) the issue. It seems though on current master that this was already changed.

@pnowack I have tried to apply the following patch on top of [d6ab9d5](https://github.com/FreeRDP/FreeRDP/commit/d6ab9d5f63df87bb2bf1195ec85d3d8b5095f887):

```
diff --git a/server/shadow/shadow_client.c b/server/shadow/shadow_client.c
index f4c41461d..23477928e 100644
--- a/server/shadow/shadow_client.c
+++ b/server/shadow/shadow_client.c
@@ -484,8 +484,8 @@ static BOOL shadow_client_post_connect(freerdp_peer* peer)
 	/* Resize client if necessary */
 	if (shadow_client_recalc_desktop_size(client))
 	{
-		shadow_send_desktop_resize(client);
-		return FALSE;
+		if(shadow_send_desktop_resize(client))
+			return FALSE;
 	}
 
 	shadow_reset_desktop_resize(client);
```

as you suggested but I obtained the same behavior.

**Comment by efferre79** [comment]
tested this morning with FreeRDP version 3.1.1-dev0 (git f6a208f75), the problem is still present

**Comment by akallabeth** [comment]
@efferre79 could you create new logs? we´ve fixed a few things and added new log messages, so that might give us a lead on what is broken when run on your setup. (can´t reproduce here :/)

**Comment by efferre79** [comment]
@akallabeth [here](https://gist.github.com/efferre79/3013ebfd69d46a60c9120bc2de05635a) is the log obtained with FreeRDP version 3.1.1-dev0 (git af9e74273)

**Comment by akallabeth** [comment]
@efferre79 you might want to retry with https://github.com/FreeRDP/FreeRDP/pull/9751 applied. This fixes broken message handling of the server in a deactivate/reactivate sequence. (that is what happens on desktop resize)

**Comment by efferre79** [comment]
@akallabeth  I have tested FreeRDP version 3.1.1-dev0 (git d1a159c48), now it is way better, I could successfully connect for 50 times in a row. But sometimes the problem still shows up, maybe there is a limit case not covered by the code. [Here](https://gist.github.com/efferre79/8d8752e20fc0d86553448a4e927914c0) is attached the logging of last bad event I achieved.

**Comment by akallabeth** [comment]
@efferre79 good to know.
I´d try a build with less debug flags now, specifically `WITH_DEBUG_RINGBUFFER` and `WITH_DEBUG_NLA` (you should change your passwords, with `WITH_DEBUG_NEGO` enabled you might be able to reconstruct it from the logs)

**Comment by akallabeth** [comment]
@efferre79 also, created https://github.com/FreeRDP/FreeRDP/pull/9757 to add some debug log entries for gfx cache import offer and reply (that is the last relevant entry in your log, so maybe something is off with that)

**Comment by efferre79** [comment]
@akallabeth I have reduced the debug flags as suggested, waiting for the merge of #9757 to retest again. The password is a dummy one for these tests so no problem.

**Comment by efferre79** [comment]
@akallabeth [Here](https://gist.github.com/efferre79/3500dbe8d3122c87381c28157e09d841) is the latest log obtained with #9757 included and the problem is visible.

I have discovered an interesting way to replicate deterministically the problem. I have a parallel x11vnc session opened at the same time between the client and server PCs. If I interact with the remote desktop via vnc (e.g. by scrolling a window with the mouse wheel) when the RDP client is trying to establish the connection then the error is likely to appear. If I leave the vnc connection open but in background (window minimized), then I don't see any problem with the connection of the RDP client. 

I guess that the RDP server is starting to get some data from the X11 server when the connection is going to be established but the working condition changes if the mouse is moved via vnc. And this later causes the problem. Next week I can verify if the same problem if repeatable when I move the real mouse on the server. 

To clarify, when I discovered and opened this issue I was not using in parallel vnc to connect to the remote server.

**Comment by akallabeth** [comment]
this sounds like a different issue now, you get past the login correct?
(also, I specifically mentioned disabling `WITH_DEBUG_RINGBUFFER` these messages are really useless ;))

I assume `mstsc` is still very unspecific in its error message? (if there is one at all?)

**Comment by efferre79** [comment]
>  (also, I specifically mentioned disabling `WITH_DEBUG_RINGBUFFER` these messages are really useless ;))

oops, I misread your suggestion and left enabled only those flags :-D Now I have removed only those two flags, [here](https://gist.github.com/efferre79/03d92e182ccf5b8eb813794427031b07) is the log. In the log now there are some lines you don't expect (from x11_shadow_input_keyboard_event) because I have patched the source to debug keystrokes transmitted to the server.

I think that the login phase has been always passed, when the problem shows up I have the impression to see for a fraction of second the remote display and then the connection is closed with the reported error. I don't know if the problem is the same but I still get the error described [above](https://github.com/FreeRDP/FreeRDP/issues/9660#issuecomment-1858773362).

BTW now I am able to replicate quite easily (100% of tries) the problem, it is sufficient to try connecting to the remote desktop where there is an application actively changing the screen image (e.g. an application in a console which is continuously writing to its stdout, I use `cat /dev/random` in a terminal). I can even replicate by using Xephyr as you suggested [here](https://github.com/FreeRDP/FreeRDP/issues/9660#issuecomment-1858313532) where the xterm command is replaced with

`DISPLAY=:23 xterm -e cat /dev/random &`

**Comment by efferre79** [comment]
@akallabeth were you able to reproduce with Xephyr?

Today I have tested again freerdp updated to latest commit from master. For each test I have started again the server and done a single connection from the client. Here are the logs of the [successful](https://gist.github.com/efferre79/459c2daefab7e1c846a4e541f33c4737) and [unsuccessful](https://gist.github.com/efferre79/43780142faa7764938ce58a2e448eeb8) connections. The latter has been achieved with the trick explained above using /dev/random.

I stripped the logs, hacked the pointers to be identical between the two sessions and reordered the lines to simplify a diff comparison. I noticed a missing call to nego_read_request_token_or_cookie() and missing input events from the unsuccessful connection, moreover avc444_compress() complains about unchanged luma or chroma frames in the unsuccessful connection. Then there are some differences close to the end. I hope there is some interesting evidence for who understands the protocol.

**Comment by akallabeth** [comment]
@efferre79 sorry, did not have time, hope next week.

**Comment by akallabeth** [comment]
@efferre79 ok, I found your issue.

Basically it boils down to:
1. The [[MS-RDPEGFX]](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegfx/da5c75f9-cd99-450c-98c4-014a496942b0)  channel requires to exchange capablilities on startup
2. The server must wait for the client to respond
3. We do not do that and expect the exchange to be finished before we send the first resetGraphics, SurfaceCommand, ...

so, renaming the issue and checking how I can fix this.

**Comment by akallabeth** [comment]
@efferre79 ok, looks like I nailed the issue.
It was indeed a (sometimes) premature graphics update that broke the connection as the client did not yet send the capability response message.

at least in my tests there were no failed connection attempts after that.

thank you for the nice test setup description you gave (the `DISPLAY=:23 xterm -e cat /dev/random &` was hammering out graphics updates and therefore triggering this really often)

**Comment by efferre79** [comment]
@akallabeth tested, now looks good! thanks!
